### ISSUE TITLE
Get-VmsCameraDiskUsage Error

### ISSUE THREAD

**Issue by subbuun** [MilestoneSystemsInc/PowerShellSamples#100]
[Get-VmsCameraDiskUsage error.txt](https://github.com/MilestoneSystemsInc/PowerShellSamples/files/12424444/Get-VmsCameraDiskUsage.error.txt)

Please advise on the error I'm getting while running the command - Get-Hardware | Get-Camera | Get-VmsCameraDiskUsage | Out-GridView

**Comment by Tarterman** [comment]
Is Get-VmsCameraDiskUsage a function that you wrote?  I can see it is referencing Get-IServerProxyService which is not part of the main MilestonePSTools module.  It was part of an unsupported extension that has been removed.

**Comment by subbuun** [comment]
![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/141190871/1e64b7c8-8427-43eb-a73e-43d7d1cffce0)

No this is part of the MilestonePSTool PowerShellSamples as in the attached snap

**Comment by Tarterman** [comment]
OK, I see it now.  It used an unsupported API via the extension module I was referring to but it was decided to remove that extension module (because it was unsupported).  Get-VmsCameraReport, which is built into MilestonePSTools will show the disk usage of each camera though.

**Comment by subbuun** [comment]
Okey great thanks. The Get-VmsCameraReport is working fine for me.
