### ISSUE TITLE
How to check whether a camera is PTZ-enabled or not?

### ISSUE THREAD

**Issue by chriswiggins** [MilestoneSystemsInc/PowerShellSamples#103]
Hi team,

Wondering if anyone has any pointers as to how we can find out whether or not a camera is PTZ-enabled? I can see that there is a `PtzSettings` property on the `ServerCommandService.CameraInfo` class, which has a `PtzEnabled` property inside it, but I can't for the life of me work out how to get that via the ConfigurationAPI.

**Comment by Tarterman** [comment]
Hi Chris,

When I get back to work on Tuesday I can help you if someone else hasn't
done so before then.  I've done some stuff recently related to PTZ cameras.

**Comment by Tarterman** [comment]
I found two ways and there might be others.  The first way is "ugly" but will return a "true" if the camera has PTZ functionality that is enabled and false if it doesn't.  The below assumes you have a camera object assigned to the $cam variable.

```
(((Get-ConfigurationItem -Path $cam.DeviceDriverSettingsFolder.DeviceDriverSettings.Path).Children | Where-Object DisplayName -eq "Pan-Tilt-Zoom").Properties | Where-Object Key -eq 'deviceptz:0.0/PTZEnabled/338d6db1-160e-4cac-a5d4-3fcf8068a955').Value
```

This will return either a "true" or a "false" indicating if the camera is PTZ enabled or not.

The other thing you can do the command below (it also assumes a camera object is assigned to the $cam variable):

```
[string]::IsNullOrEmpty($cam.DeviceDriverSettingsFolder.DeviceDriverSettings[0].PTZSessionTimeoutChildItem)
```

If it returns "true" then PTZ functionality is NOT enabled on the camera.  If it returns "false" then PTZ functionality is enabled.  Basically, if a camera has PTZ functionality enabled then there will be some settings and info in PTZSessionTimeoutChildItem so it is just checking if there is anything there.

**Comment by joshooaj** [comment]
Another way to retrieve cameras with PTZ enabled is to use the objects returned by one of the `VideoOS.Configuration.Instance.GetItem*()` methods.

The `Get-VmsVideoOSItem` cmdlet can be used to retrieve all cameras with PTZ enabled using...

```powershell
Get-VmsVideoOSItem -Kind Camera -FolderType No | Where-Object { $_.Properties['PTZ'] -eq 'Yes' }
```

Each device item will have a Properties dictionary. My test StableFPS camera has the following properties on the `CameraItem` object returned by `Get-VmsVideoOSItem`:

```
Key           Value
---           -----
PTZ           No
Ipix          No
PanoramicLens No
ShortCut
EdgeSupported Yes
Channel       0
```
