### ISSUE TITLE
Request for hardware update

### ISSUE THREAD

**Issue by Jaffe1986** [MilestoneSystemsInc/PowerShellSamples#106]
We are updating Firmware on our devices via Postman. In order for new FW version to show correctly in management client we must right click on each device and select "update hardware".

is there a way to do the update hardware or even replace hardware via PowerShell

**Comment by Tarterman** [comment]
This functionality was added in the 2023 R1 version of the MIP SDK and was then added to MilestonePSTools.  So, as long as the version of software you are running is 2023 R1 or newer and you are running the latest version of MilestonePSTools, then you are able to do this.  It is done using the Set-VmsHardwareDriver cmdlet.  If you pass a hardware object to it (e.g., $hardware | Set-VmsHardwareDriver) and don't specify anything else, then it is the same as doing a Replace Hardware in the Management Client and not actually changing anything.

**Comment by Jaffe1986** [comment]
Thank you
