### ISSUE TITLE
Read & Trigger Permission per Role

### ISSUE THREAD

**Issue by Jaffe1986** [MilestoneSystemsInc/PowerShellSamples#107]
I would like to script the permission assignment of User-defined Events. I have yet to find a good way to do this. By editing the properties hash table for the Role i can give permission to read and trigger ALL events but I need to be able to assign them explicitly.(EXAMPLE: Role: 0064 has Read & Trigger permission for User-defined Event: 008 but not to 009)  Is there an option I am overlooking? 

I will also note that the ability to sort User-defined events in the same way we do device group would be amazing. I don't know who needs to here this but Event Groups needs to be a thing.

**Comment by joshooaj** [comment]
Unfortunately the MIP APIs do not yet support granular permission management on objects besides devices attached to hardware (cameras, mica, speakers, etc) and view groups. But I'm told it's coming in the next release or two and any "MIP item" permissions would be manageable including permissions for items added by integrations.

I hear you on the grouped events. I've often wanted to be able to group recording servers and other flat item collections.
