### ISSUE TITLE
Question on ACM Integration

### ISSUE THREAD

**Issue by kingb2019** [MilestoneSystemsInc/PowerShellSamples#110]
I have a need to be able to execute the refresh configuration action in the Access Control portion of Milestone XProtect Management Client > Access Control > General Settings tab. This uses the ACM Access plugin to pull in updated data from Lenel Onguard (or CCure 9000). Is there a way to do this via PS Tools?

**Comment by Tarterman** [comment]
I could be missing something but I couldn't find any support in the SDK for refreshing the configuration.  It looks to be something that was only implemented in the Management Client itself.

**Comment by joshooaj** [comment]
Closing stale issue
