### ISSUE TITLE
using -updateExisting outside of the excel module

### ISSUE THREAD

**Issue by AmineDZT** [MilestoneSystemsInc/PowerShellSamples#111]
Im trying to update multiple devices on mac adress. The only way I can seem to export a list that contains the MAC is with get-vmsCamerareport. Is there a way to import this CSV using the updateExisting flag?

**Comment by joshooaj** [comment]
Hi @AmineDZT,

Sorry, no there is no opposing command for `Get-VmsCameraReport`. At some point I expect we'll revise the export/import-vmshardware commands with support for importing changes to existing items. Until then, you have all the tools you need between MilestonePSTools, the [`Export/Import-VmsHardwareExcel`](https://www.milestonepstools.com/tools/import-hardware-from-excel/) working sample, and the [MIP SDK documentation](https://doc.developer.milestonesys.com/html/index.html).

You can get the MAC, serial number, and last known firmware for a given hardware item using the `Get-HardwareSetting` command which returns a collection of general setting keys and values. For example, here's a one-liner to get all the hardware names, addresses, models, and the serial values from the hardware general settings.

```powershell
Get-VmsHardware | Select-Object Name, Address, Model, @{ Name='Serial'; Expression={ ($_ | Get-HardwareSetting).SerialNumber } }
```

And here's another way you might export a few more hardware properties...

```powershell
Get-VmsHardware | ForEach-Object {
    $driver = $_ | Get-VmsHardwareDriver
    $general = $_ | Get-HardwareSetting
    $password = $_ | Get-VmsHardwarePassword
    
    [pscustomobject]@{
        Name          = $_.Name
        Address       = $_.Address
        UserName      = $_.UserName
        Password      = $password
        Model         = $_.Model
        Firmware      = $general.FirmwareVersion
        DriverNumber  = $driver.Number
        DriverVersion = $driver.DriverVersion
        SerialNumber  = $general.SerialNumber
        MacAddress    = $general.MacAddress
    }
} | Export-Csv -Path ./hardware-properties.csv
```
To import changes to hardware using the MAC as a lookup key, I'd recommend importing the CSV and storing each row in a hashtable with the MacAddress column as the key...

```powershell
$changes = @{}
Import-Csv -Path ./hardware-properties.csv | ForEach-Object {
    $changes[$_.MacAddress] = $_
}
```

Then perhaps use `Get-VmsHardware` to enumerate all the hardware, `Get-HardwareSetting -Hardware $hardware` to retrieve the MAC from the VMS, then check your hash table for the MacAddress value. If it's in there, use `Set-VmsHardware` for example to change settings on the VMS to match the values from the CSV/hash table.

**Comment by joshooaj** [comment]
Closing stale issue
