### ISSUE TITLE
Get-VMSHardware Serial Number

### ISSUE THREAD

**Issue by Jaffe1986** [MilestoneSystemsInc/PowerShellSamples#115]
I have a customer who wants to refer to their Cameras by Serial Number. I've tried everything I can think of with get-VMSHardware but have not come any closer to finding where the Serial Number is stored. Is pulling this piece of information possible at the moment?

I was hoping i could find it simply with something like

$cam = get-VMSHardware -name "Name"
write-host $cam.SerialNumber

**Comment by joshooaj** [comment]
Hi @Jaffe1986,

The serial number, MAC address (often the same but not always), and other general hardware properties are available using Get-HardwareSetting:

$hardware | Get-HardwareSetting

Does that give you what you need?

**Comment by Jaffe1986** [comment]
Aww @joshooaj 

You are a live saver. This is exactly what I need.
