### ISSUE TITLE
Connect-ManagementServer returns Object reference error

### ISSUE THREAD

**Issue by jmisty** [MilestoneSystemsInc/PowerShellSamples#116]
MilestonePSTools version: 23.3.1
Milestone version: 2019 R2
OS: Windows Server 2019 Std build 10.0.17763

Issue:
The Connect-ManagementServer cmdlet doesn't work correctly with my setup and returns the following error:

```
Connect-ManagementServer : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-ManagementServer -AcceptEula -ShowDialog
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-ManagementServer], NullReferenceException
    + FullyQualifiedErrorId : Object reference not set to an instance of an object.,MilestonePSTools.ConnectionCommand
   s.ConnectManagementServer
```

If using -ShowDialog the GUI does appear, but the same thing happens when I click on login.
The same error was shown when I installed version 23 from the gallery.

Any idea what the problem could be? 
(I just need to export the stream properties of all cameras to a CSV file but in order to do so I first need to connect using that cmdlet).

![Screenshot from 2023-11-28 12-54-39](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/47589610/354e304d-35d9-4ce6-8975-60ca864ac732)

Many thanks.

**Comment by Tarterman** [comment]
@jmisty, I can reproduce this on my 2019 R2 system.  Troubleshooting it goes beyond my ability because the errors reference the C# code so @joshooaj will have to look into it.  Josh, here's more details on the error.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/5066904e-7fba-4a39-9524-5b7ebbb8ccdb)

Using the new Connect-Vms produces this.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/f6bfe08f-7daf-4946-8091-f9b3ac72bbe6)

**Comment by joshooaj** [comment]
Hi @jmisty,

I finally had a chance to dig into this and there seems to be some compatibility issues between the latest version of MIP SDK and 2019 R2. Probably older versions too, and maybe even some versions newer than that - I'm not sure yet.

Our products and MIP SDK have a limited support period, and versions older than 2020 R1 are terminated according to our [product lifecycle](https://www.milestonesys.com/support/software/product-lifecycle/) which means it may not be possible for our SDK team to find and fix the compatibility issue.

From what I can tell from the behavior in PowerShell and some of the errors logged in `C:\ProgramData\Milestone\MIPSDK\`, it seems like some API calls made in the background between MIP SDK and the management server fail, but not spectacularly enough to get a `ServerNotFoundMipException` or some other more meaningful error.

I can successfully login using the .NET classes/methods from our SDK in PowerShell, but the LoginSettings object that is supposed to include the ID of the site shows an empty GUID instead.

Similarly, calling `Configuration.Instance.GetItems()` returns a Management Server item where the ObjectId, ParentId, and ServerId all have empty guids.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/25234b21-2cb8-41ae-a8d1-e13150a42ac4)

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/8390e2e7-cea7-49cf-8504-9e4fc6cab5e1)

**Comment by jamesangi** [comment]
I was just about to open the same issue, but I'm seeing this on 2020R3 so maybe there is hope for it to be fixed after all?

**Comment by thatonegeekguy** [comment]
Encountering the same issue here using latest MilestonePSTools as of 1/15/2023 from the Gallery. 2023R1 system still presents the problem outlined above. Reverting to version 23.2.3 resolves the issue.

It should be noted that the latest version of MilestonePSTools installed via NuGet from the Powershell Gallery is 23.3.1 yet installs the MilestonePSTools.dll with the version of 23.3.3. The Project version needed to be updated to allow a successful import of the module. I'll open a separate Issue ticket for that, if needed.

**Comment by Z4YA** [comment]
Same issue - MilestonePSTools v23.3.1 / 2020R2

**Comment by codypaternostro** [comment]
Tested Milestone versions 2019 R3, 2020 R1, 2020 R2, 2020 R3, 2022 R1 and was able to replicate the issue with these so far.

**Comment by joshooaj** [comment]
This issue is related to an unknown (to me) change in the 23.3 SDK. It seems only basic users work on VMS versions older than 2021 R1.

It's been reported to the MIP team but I'm not sure if anything will be changed to resolve it given the issue is only present on discontinued VMS versions as far as I can tell.

Either way we can add a better error message for this unique issue to the module.

**Comment by joshooaj** [comment]
Closing stale issue.
