### ISSUE TITLE
2014 Export to Import Into 2018?

### ISSUE THREAD

**Issue by starkmatt** [MilestoneSystemsInc/PowerShellSamples#12]
Josh,
Big Ups to you for putting in the effort into creating this module.
It's been great.

Unfortunately, I have a particular circumstance with a Client which have about 100 - 150 VM's that are running 2014.
There is a project to move these across to 2018 Federated Architecture.
I can get an export of the 2014 Configuration using the function you've left as an example

```
##Export Hardware
$hardwareInfo = New-Object -TypeName System.Collections.ArrayList
foreach ($rec in Get-RecordingServer)
{
    foreach ($hardware in $rec | Get-Hardware)
    {
        $driver = $hardware | Get-HardwareDriver

        $row = New-Object -TypeName PSObject
        $row | Add-Member -MemberType NoteProperty -Name Name -Value $hardware.Name
        $row | Add-Member -MemberType NoteProperty -Name Enabled -Value $hardware.Enabled
        $row | Add-Member -MemberType NoteProperty -Name Address -Value $hardware.Address
        $row | Add-Member -MemberType NoteProperty -Name UserName -Value $hardware.UserName
        $row | Add-Member -MemberType NoteProperty -Name Password -Value ($hardware | Get-HardwarePassword)
        $row | Add-Member -MemberType NoteProperty -Name MacAddress -Value ($hardware | Get-HardwareSetting).MacAddress
        $row | Add-Member -MemberType NoteProperty -Name DriverName -Value $driver.Name
        $row | Add-Member -MemberType NoteProperty -Name DriverNumber -Value $driver.Number
        $row | Add-Member -MemberType NoteProperty -Name HardwareId -Value $hardware.Id
        $row | Add-Member -MemberType NoteProperty -Name RecordingServerName -Value $rec.Name
        $row | Add-Member -MemberType NoteProperty -Name RecordingServerId -Value $rec.Id        
        $hardwareInfo.Add($row)
    }
}

$hardwareInfo | Export-Csv -Path c:\sources\dump04.csv -NoTypeInformation -Force

```

As the script is generating Hardware export for each camera on the 2014 VM there seem to be some parameters missing ?
An error appears on screen
```
Export-HardwareCsv : Failed to retrieve info for Axis 2 channel device (192.168.1.117). Error: Sequence contains no matching element
At line:1 char:29
+ ... me *axis* | Export-HardwareCsv -Path C:\temp\hardware.csv -Full -Verb ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-HardwareCsv
 

```

For example the export will look like the following;

```
"Name","Enabled","Address","UserName","MacAddress","DriverName","DriverNumber","HardwareId","RecordingServerName","RecordingServerId"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90BB36",,,"0021228E-E2D2-4C34-A401-6ED596B10434","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B3C8",,,"0554BBDC-0081-4D67-8A5C-4754E9EB6642","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 8 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8EA5FF35",,,"0A62E7DB-523E-4C60-860E-E3BC8847612A","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B9E4",,,"0E15759D-40C5-4784-BF39-EC27042FD09D","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B3E7",,,"189C6420-C032-492B-9703-F4E098B0A919","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E9DCE5D",,,"256BE7DF-B36E-455A-987D-B571342B9562","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B9F8",,,"2950B5D6-67CC-4867-9C72-B45EFAFE764C","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 8 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E984BFD",,,"2F02EC7E-2F5D-48EC-82D7-FBF6D6AA3BE8","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B3F0",,,"38ECF915-F206-4696-AE1E-F70143F3A097","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E90B9F5",,,"3F1CCED7-39A5-4764-A665-8635B7C04800","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E9DCE94",,,"4A3B6269-6BBC-4187-9F8E-4F1AE6D6FA26","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
"Axis 2 channel device (192.x.x.x)","True","http://192.x.x.x/",,"ACCC8E9D907C",,,"4C6C7334-58F8-4FAB-BE18-E646681D567E","BXXXXXXXX","3F08E14C-ACE5-4D72-9221-ECE96A62C1E8"
```

_PS I've added X for sensitive Data_

When the 2014 Export has completed, we then move onto the 2018 VM.
Firstly we connect to the Federated Management, 

```
Connect-Management -Server xxxxx.xxxx.com -AcceptEula
```

Then we specifiy the recording server
```
Get-Recording Server -Name XXXXX
```
After selecting the new Recording server, we try

```
Import-HardwareCSV -Path C:\temp\hardware.csv
```

After running this, we can see that it's sequentially running through each line but it returns the following 
```
Import-HardwareCsv : Exception calling "Add" with "2" argument(s): "Key cannot be null.
Parameter name: key"
At line:1 char:1
+ Import-HardwareCsv -Path C:\temp\hardware01.csv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-HardwareCsv
```

My suspicions are that the export is missing some Data.
You have a demo here 

https://www.youtube.com/watch?v=zYRBfRtnCJo

Which shows that once you have a hardware export to CSV there is a json file created along side for configuration.
When we try to export, it doesn't come with a json and also the Password / Username are missing also.

Have you had to deal with this before?

Thanks again!

**Comment by jhendricks123** [comment]
Hi Matt,

I don't think the script you're using to produce the CSV is compatible with the Import-HardwareCsv cmdlet which is designed to take the output of the Export-HardwareCsv cmdlet.

Basically Export-HardwareCsv does the same thing as the export script you pulled from the samples, but I think there's a header name difference in there somewhere.

If you use Export-HardwareCsv with the -Full switch, it will produce the corresponding json files for each hardware device which contains all the Configuration API properties for the hardware and all child objects which can be used with Import-HardwareCsv -Full to try to mirror the configuration on the target system as closely as the Configuration API allows.

A couple of things to note:

1. You may see some errors/warnings on export about a key not being found. There was a particular couple of Device Pack versions where we were introducing new features around device password management when the driver team did not include a GUID for the new and yet unused features - this caused an error whenever trying to access hardware properties visible in the General tab of the hardware device in Management Client. The MAC address is a read-only property in that same area, so when I try to retrieve the MAC on export, it would fail to read it. Upgrading the device pack would resolve that issue though.

2. It's a good idea to make sure the same device pack version is installed on both the old and new recording servers. Drivers change a little over time, and if the driver versions don't match when you use the -Full switch, the import may not be able to apply the settings from the old cameras at all. They'll be added, but they won't get configured with the appropriate names and enabled/disabled status among other things.

**Comment by jhendricks123** [comment]
Hi Matt,

Hopefully your questions were answered - if not, please don't hesitate to post another issue. I'll go ahead and close this one now just to tidy things up.

Cheers,

Josh
