### ISSUE TITLE
V23.3.2: Connect-ManagementServer failed with AD user

### ISSUE THREAD

**Issue by jiemjiem** [MilestoneSystemsInc/PowerShellSamples#132]
Hello, 
Since upgrade in 23.3.2, we are unable to connect with our default AD user
(test with 2 users on 2 clients Win10, powershell 5.1 and 7, Milestone 2020 R3)
Connection is OK with a local Milestone Account.

No problem at all in 23.2.1 

Error returned:
Connect-ManagementServer  xxx
Connect-ManagementServer : Something went wrong during the login process. EnvironmentManager.Instance.GetSiteItem returned null. The LoginSettings guid for the
attempted login is '00000000-0000-0000-0000-000000000000'
Au caractère Ligne:1 : 1
+ Connect-ManagementServer  xxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError : (:) [Connect-ManagementServer], ArgumentNullMIPException
    + FullyQualifiedErrorId : Something went wrong during the login process. EnvironmentManager.Instance.GetSiteItem returned null. The LoginSettings guid for the
    attempted login is '00000000-0000-0000-0000-000000000000',MilestonePSTools.ConnectionCommands.ConnectManagementServer

**Comment by Tarterman** [comment]
@jiemjiem, this is an "issue" with the latest SDK. It broke compatibility with versions older than 2021 R1. The only option is to continue using MilestonePSTools 23.2.1 until the Milestone software is updated to a newer version.

You can also find a compatibility chart that was recently added to the MilestonePSTools documentation here:

[MilestonePSTools Compatibility](https://www.milestonepstools.com/installation/#compatibility)
