### ISSUE TITLE
Get-VmsRule Timeout

### ISSUE THREAD

**Issue by Jaffe1986** [MilestoneSystemsInc/PowerShellSamples#134]
I find it weird I haven't needed to run this command until now, but I always get a timeout error when I run Get-VmsRule.

Get-VmsRule : The request channel timed out while waiting
for a reply after 00:04:59.9979784. Increase the timeout
value passed to the call to Request or increase the
SendTimeout value on the Binding. The time allotted to
this operation may have been a portion of a longer timeout.
At line:1 char:1
+ Get-VmsRule -Name 'front -5 Minute Live Stream'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Err
   or], TimeoutException
    + FullyQualifiedErrorId : System.TimeoutException,Get-
   VmsRule

I've tried to get a list of all the rules.
'''
Get-VmsRule
'''
Searching for a single rule.

'''
 Get-VmsRule -Name 'front -5 Minute Live Stream'
'''

I've tried the suggestions listed in the error message. 

any help would be appreciated.

**Comment by Tarterman** [comment]
@Jaffe1986, what version of XProtect are you using and what version of MilestonePSTools are you using?

Also, can you run Get-VmsRule again to get the error and then run the following and post the output of both commands here:

```
$error[0] | format-list * -force

$error[0].Exception | format-list * -force
```

**Comment by Jaffe1986** [comment]
Thank you so much for the quick response. This is we your team is the best.

I am sorry, I discovered I had 2 different versions of MilestonePSTools installed side by side, I don't know what the conflict was but when I uninstalled the older version, everything started to work.
