### ISSUE TITLE
Get-VmsRoleOverallSecurity : how to disable error message process

### ISSUE THREAD

**Issue by tobitanaka** [MilestoneSystemsInc/PowerShellSamples#136]
Question: Is there a way to prevent the following error message from appearing?

----
Get-VmsRoleOverallSecurity : Overall security settings do not apply to the Administrator role.
Occurrence location: Line 1, Character 15
+ Get-VmsRole | Get-VmsRoleOverallSecurity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-VmsRoleOverallSecurity
----

Note: My understanding is that 'Get-VmsRole | Get-VmsRoleOverallSecurity -ErrorAction SilentlyContinue' only prevents the error from being output to the console, but does not skip the error processing.

[Environment information]
OS: Windows Server 2019
PS: PowerShell 5.1
Module: MilestonePSTools 23.3.4, MipSdkRedist 23.2.1

**Comment by joshooaj** [comment]
Hi @tobitanaka, you can use [Get-VmsRole -RoleType UserDefined](https://www.milestonepstools.com/commands/en-US/Get-VmsRole/#example-3) which will automatically skip the Administrators role. Will that work for you?

**Comment by tobitanaka** [comment]
Thank you @joshooaj , I will process further with the user m(_|_)m

**Comment by tobitanaka** [comment]
Hi @joshooaj , the customer has sent the appreciation as follows to the provided solution, thank you again:

I was able to resolve it using the method you taught me. Thank you very much.
'Get-VmsRole -RoleType UserDefined | Get-VmsRoleOverallSecurity'

I have closed this case.
