### ISSUE TITLE
Question for Get-VmsCameraReport

### ISSUE THREAD

**Issue by tobitanaka** [MilestoneSystemsInc/PowerShellSamples#138]
Please advise for following customer's query for Get-VmsCameraReport:

* his question for following 4 items in the report columns, ref link:
https://www.milestonepstools.com/commands/en-US/about_Get-VmsCameraReport.help/#summary-of-all-potential-columns

4 items:

ConfiguredLiveCodec
CurrentLiveCodec
ConfiguredRecordedCodec
CurrentRecordedCodec

3 Questions:

> What is the difference between configured and current for LiveCodec?
> What is the difference between configured and current for RecordedCodec?
> Which server's resources (recording server? or mobile server?) is used by LiveCodec and RecordedCodec?  <<<<<<< it may be Recording Server resource, am I correct?

**Comment by tobitanaka** [comment]
Hi,
It is appreciated that any update may be provided that enable me for further process of this issue, thank you in advance.

**Comment by Tarterman** [comment]
Hi @tobitanaka,

The "configured" value will show the value that is configured in our software. The "current" value is showing what the actual stream is. For example, it could be possible that you set the camera to h.264 in our software but, for some reason, the camera didn't set itself to that and is still sending MJPEG.

In short, the values for "configured" and "current" should match each other. If they don't match then something is wrong (i.e., the camera didn't receive the settings change or something like that).

These settings are all related to the Recording Server.

**Comment by tobitanaka** [comment]
Hi Tarterman, @Tarterman 

Thank you for the guidance for the difference between "configured" and "current" with elaboration, understood and appreciated.
I will liaise with the customer accordingly.
