### ISSUE TITLE
Name Update? 

### ISSUE THREAD

**Issue by jdennis319** [MilestoneSystemsInc/PowerShellSamples#145]
Hello, 

I am looking to update the names of a few thousand cameras within Milestone. Is there an existing script or method to pull the currently installed devices, adjust their names, and reload them into the system? If so, could you provide guidance or an example of how this would be implemented?

Thank you for your assistance.

Jeremy

**Comment by Tarterman** [comment]
Hi @jdennis319,

If you just need to change camera names, you could do something like this:

Export the current names to a CSV
`Get-VmsCamera | Select-Object Id, Name | Export-Csv cameras.csv`

Make the desired changes and then import it back in:
`Import-Csv .\cameras.csv | % { $_ | Get-VmsCamera | Set-VmsCamera -Name $_.Name -WhatIf }`

The "-WhatIf" at the end will run through everything without making actual changes but it will show the changes it would have made in the console. If everything looks good, run the second command again but remove the "-WhatIf" off the end.

**Comment by jdennis319** [comment]
Thank you, that worked out well! 

-Jeremy

**Comment by jdennis319** [comment]
Thanks again
