### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by aoforb** [MilestoneSystemsInc/PowerShellSamples#146]
Before I go down the rabbit hole... Has anyone got this API to work with Ubuntu using the PowerShell 7 package?

**Comment by joshooaj** [comment]
That makes perfect sense, thanks for sharing! I'm happy to see someone using the module in an IaC strategy, even if it can be a bit of a square peg in a round hole as a Windows-only module.

I'll close this and make sure to take another look at our openapi spec soon.
