### ISSUE TITLE
Set-VmsCamera -RecordingEnabled not working

### ISSUE THREAD

**Issue by granttfo** [MilestoneSystemsInc/PowerShellSamples#148]
`Set-VmsCamera -RecordingEnabled $true` and `Set-VmsCamera -RecordingEnabled $false` both have the same effect, turning OFF the recording checkbox in the camera.

`Get-VmsCamera` returns the current setting correctly.

Using XProtect Professional+ 2024 R1

**Comment by joshooaj** [comment]
Well that's not good. I'll take a look at this tomorrow - thanks for the report!

**Comment by joshooaj** [comment]
Hi @granttfo,

I'm not able to reproduce this on XProtect Professional+ 2024 R1 with MilestonePSTools v24.1.9. Here are the commands I ran:

```powershell
$camera = Select-Camera -SingleSelect

$camera | Set-VmsCamera -RecordingEnabled $false -Verbose

# In Management Client, the camera now has recording disabled in the camera > record tab

$camera | Set-VmsCamera -RecordingEnabled $true -Verbose

# In Management Client, the camera now has recording enabled in the camera > record tab
```

If you're still seeing the problem, what happens if you modify the `$camera` object directly and then call the `Save()` method like this:

```powershell
$camera.RecordingEnabled = $false
$camera.Save()

# Check Management Client

$camera.RecordingEnabled = $true
$camera.Save()

# Check Management Client again
```
