### ISSUE TITLE
Easier way to extract the used license information?

### ISSUE THREAD

**Issue by chriswiggins** [MilestoneSystemsInc/PowerShellSamples#15]
To pull out how many licenses are currently being used by Milestone, we're running the following:

```powershell
((((Get-ManagementServer).LicenseInformationFolder.LicenseInformations.LicenseOverviewAllFolder |
 Get-ConfigurationItem -ChildItems) | 
Where-Object -Property "DisplayName" -eq "Hardware Device").Properties | 
Where-Object -Property "TranslationId" -eq "PropertyLicenseActivated").Value
```

Is there an easier or better way of doing this?

Thanks!

**Comment by chriswiggins** [comment]
I just found the `Get-LicenseDetails` cmdlet. Ignore me :-)

**Comment by jhendricks123** [comment]
Hi Chris,

That's pretty much how you have to do it. The license information is essentially just an XML document and our SDK team have enabled the Configuration API to return properties of that document in the ConfigAPI format. You can check out the xml document yourself by running `$xml = [xml](Get-IServerProxyService).GetLicenseInformation()` and exploring that $xml XmlDocument object. For example, `([xml](Get-IServerProxyService).GetLicenseInformation()).LicenseInformation.TotalActivated.HardwareCount` would give you the total hardware count across all activations of the SLC.

I wrote that Get-LicenseDetails cmdlet before our SDK team made the information available via ConfigAPI and I did so by parsing out the interesting bits (interesting to me) of that XML document.

Here are a couple of short functions for building pscustomobjects out of the license information returned by Config API in case it comes in handy:

```powershell
function Get-LicenseOverview {
    process {
        $result = @{}
        $site = Get-Site
        Get-ConfigurationItem -Path "LicenseInformation[$($site.FQID.ObjectId)]/LicenseOverviewAllFolder" -ChildItems | ForEach-Object {
            $properties = @{}
            $_.Properties | ForEach-Object {
                $properties.$($_.Key) = $_.Value
            }
            $result.$($_.DisplayName) = [pscustomobject]$properties
        }
        Write-Output ([pscustomobject]$result)
    }
}

function Get-LicenseDetail {
    process {
        $result = @{}
        $site = Get-Site
        Get-ConfigurationItem -Path "LicenseInformation[$($site.FQID.ObjectId)]/LicenseDetailFolder" -ChildItems | ForEach-Object {
            $properties = @{}
            $_.Properties | ForEach-Object {
                $properties.$($_.Key) = $_.Value
            }
            $result.$($_.DisplayName) = [pscustomobject]$properties
        }
        Write-Output ([pscustomobject]$result)
    }
}
```

**Comment by chriswiggins** [comment]
Amazing thank you!
