### ISSUE TITLE
Wrong file for https://www.milestonepstools.com/examples/group-cameras-by-model/

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#151]
https://www.milestonepstools.com/examples/group-cameras-by-model

Download link is correct, source code is not:

![image](https://github.com/user-attachments/assets/b8469d16-f304-4874-a4f2-51614cdb1e49)

**Comment by joshooaj** [comment]
Thanks @Silex! Another copy/paste mistake - the docs are being updated now.
