### ISSUE TITLE
Merge MIPSDKRedist & MilestonePSTools -> half size?

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#152]
Hello,

It looks like *a lot* of DLLs are the same between the two projects.

I have to distribute tools based on MilestonePSTools and MIPSDKRedist is 100MB and MilestonePSTools is 170MB, so my tool unzipped folder is like 270MB 😅 I use local modules.

Looks like maybe there's a way to reduce this?

**Comment by Tarterman** [comment]
Hi @Silex,

Are you using an older version of MilestonePSTools? Starting with version [23.3.1](https://www.milestonepstools.com/changelog/#changed_6), the dependency on the independent MipSdkRedist module was removed. The MilestonePSTools module now includes all required MIP SDK assemblies. As an example, the latest version (24.1.9) is 181MB and that includes everything as it is all together now.

**Comment by Silex** [comment]
Ah, I just included the dependency out of habit! lol

Thanks :-)
