### ISSUE TITLE
Select-VideoOSItem to Hardware

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#153]
Hello,

I want to use `Select-VideoOSItem -AllowFolders -FlattenOutput` so my user can select cameras/groups/hardwares/whatever and eventually I want convert it all to Camera/Hardware/whatever.

I found `ConvertFrom-ConfigurationItem` but I don't think it'll help me there.

I guess I have to use the constructors for each item, something like `[VideoOS.ConfigurationItems.Camera]::new` but I'm not sure how to detect the type when `Select-VideoOSItem` returns different item types.

Any idea?

**Comment by Tarterman** [comment]
I'm not entirely following what you are trying to do but I do know how to detect the type from Select-VideoOSItem. One of the items returned from Select-VideoOSItem is the FQID which contains a GUID for the "Kind". So, you can do something like this to get the type (returned as DisplayName).

```
$device = Select-VideoOSItem
Get-Kind -Kind $device.FQID.Kind
```
![image](https://github.com/user-attachments/assets/e9365872-ea0d-4042-9ac8-30b07ceca491)

**Comment by Silex** [comment]
Ah, nice this should be enough to be able to call the Camera class constructor with the FQID and thus get a ConfigurationItem out of the generic Item class. Will post something on monday.

**Comment by Silex** [comment]
I did it!

``` ps1
function ConvertFrom-VideoOSItem {
  [CmdletBinding()]
  param ([Parameter(ValueFromPipeline)]
         [PSObject] $InputObject)

  process {
    $kind = Get-Kind -Kind $InputObject.FQID.Kind
    $type = 'VideoOS.Platform.ConfigurationItems.{0}' -f $kind.DisplayName
    New-Object -TypeName $type -ArgumentList $InputObject.FQID
  }
}

$items = Select-VideoOSItem -AllowFolders -KindUserSelectable -CategoryUserSelectable -FlattenOutput
$items = $items | ForEach-Object { $_ | ConvertFrom-VideoOsItem }
```

@joshooaj consider adding it 😉

**Comment by Silex** [comment]
I also implemented this:

``` ps1
function Get-ParentItem {
  [CmdletBinding()]
  param ([Parameter(ValueFromPipeline)][PSObject] $InputObject,
         [Parameter(Mandatory)] $Kind)

  process {
    $parent = $InputObject
    while ($parent.Path -ne '/') {
      if ($parent.Path -like "$Kind*") {
        return $parent
      }
      $parent = $parent | Get-ConfigurationItem -ParentItem | ConvertFrom-ConfigurationItem
    }
  }
}
```

This is meant to be used like this:

``` ps1
$cam = Get-VmsCamera | Select-Object -First 1
$hw = $cam | Get-ParentItem -Kind Hardware
$rs = $cam | Get-ParentItem -Kind RecordingServer
```

Maybe `Get-ConfigurationItem` could be extended with a `-Recurse` parameter that does the same when `-ItemType` is present?

e.g `$rs = $cam | Get-ConfigurationItem -ParentItem -Recurse -ItemType RecordingServer | ConvertFrom-ConfigurationItem`

**Comment by Silex** [comment]
Ah lol, I just discovered https://www.milestonepstools.com/commands/en-US/Get-VmsParentItem

This will make my life simpler, thanks!
