### ISSUE TITLE
Get-Snapshot LocalTimestamp issue

### ISSUE THREAD

**Issue by UfukYKO** [MilestoneSystemsInc/PowerShellSamples#155]
Hi Josh,

We are using the get-snapshot with the -localtimestamp so it uses the local time for the generated files. But it seems like it still uses the UTC time in the generated filenames. This is the generated filename:
Kamera 4_2024-10-04_06-29-49.755.jpg

We are using this prompt:
 $null = $camera | Get-Snapshot -Timestamp (Get-Date).AddHours(-4) -EndTime (Get-Date) -Interval 0.5 -Save -LocalTimestamp -Path C:\snaps\ -Quality 100 -UseFriendlyName

Are we doing something wrong?
Thanks!

![host_8qo6w6SbqC](https://github.com/user-attachments/assets/e0c0e571-7de3-4b34-abf0-377574be719c)

**Comment by UfukYKO** [comment]
> @UfukYKO, I can confirm what you are seeing on v24.1.27. It seems like a bug but I'll let @joshooaj chime in.
> 
> Here's what I'm running that still has a UTC timestamp in the file name.
> 
> ```
> Get-Snapshot -Camera $cam -Live -LocalTimestamp -Path C:\Snapshots -Save -UseFriendlyName
> ```

@Tarterman we are also using 2024 R1.

**Comment by joshooaj** [comment]
Hi @UfukYKO,

Thank you for the report! I have fixed this for the next release of MilestonePSTools. I don't have a release date for the next version but in the mean time you can reproduce the default snapshot filenames like this:

```powershell
$snapshotParams = @{
    Live     = $true
    Save     = $true
    Path     = 'C:\temp\'
    FileName = "$($camera.Id)_$((Get-Date).ToString('yyyy-MM-dd_HH-mm-ss.fff')).jpg"
}
$camera | Get-Snapshot @snapshotParams
```
