### ISSUE TITLE
Get-Role "The pipeline has been stopped." error

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#17]
Hello,

The following code creates this error:

``` powershell
PS C:\Users\philippe> Get-Role | Select-Object -First 1

UserFolder                         : Role members
Id                                 : 1F30D14B-BA91-4E8A-8838-EDA17931F8FC
RoleTypeValues                     : {[Adminstrative, Adminstrative], [UserDefined, UserDefined]}
RoleType                           : Adminstrative
LastModified                       : 28.05.2019 22:02:29
DualAuthorizationRequired          : False
MakeUsersAnonymousDuringPTZSession : False
AllowMobileClientLogOn             : True
AllowSmartClientLogOn              : True
AllowWebClientLogOn                : True
Methods                            : {SetClientTimeProfile, GetClientTimeProfile}
ServerId                           : VideoOS.Platform.ServerId
Name                               : Administrators
DisplayName                        : Administrators
Path                               : Role[1f30d14b-ba91-4e8a-8838-eda17931f8fc]
ParentPath                         : /RoleFolder
ItemCategory                       : Item
Description                        : Administrators have complete and unrestricted access to the system
ParentItemPath                     : System[]

Get-Role : The pipeline has been stopped.
At line:1 char:1
+ Get-Role | Select-Object -First 1
+ ~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-Role], PipelineStoppedException
    + FullyQualifiedErrorId : An error occurred,MilestonePSTools.PermissionCommands.GetRole
```

Not sure if this is the right behavior, even if it makes sense. How does "classic" API handle this situation?

**Comment by jhendricks123** [comment]
Thanks Silex,

This is something that was brought to my attention a few weeks ago on the Get-Log cmdlet. These cmdlets are enumerating over results and Select-Object is stopping the pipeline. I haven't read into very deeply yet but the way I fixed it for Get-Log was to add a no-op exception handler for PipelineStoppedException while writing any other error to the pipeline as an error record.

I'll make sure Get-Role doesn't write the error to the pipeline in the next release. Meanwhile you could do...

`Get-Role -ErrorAction Ignore | Select-Object -First 1`

Also I think with the way retrieving roles works when you don't have the ID of the role you want, the wait time for the above command is probably the same as...

`(Get-Role)[0]`

Which won't stop the pipeline while retrieving roles and still gives you the first one.

**Comment by Silex** [comment]
Yeah, I just wanted to bring it to your attention. Do whatever you want with this issue :wink:

**Comment by jhendricks123** [comment]
Thanks again - closing this now with the release of MilestonePSTools 1.1.0 on PSGallery
