### ISSUE TITLE
Add_Hardware_from_CSV.ps1 truncated

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#18]
Hello,

FYI it seems like https://github.com/MilestoneSystemsInc/PowerShellSamples/blob/master/Samples/Add_Hardware_from_CSV.ps1 is truncated.

**Comment by jhendricks123** [comment]
Thanks for the heads up - I'm not sure why it was never finished but I'll try to rewrite it later this week.

After looking at it I may need to make adjustments to Import-HardwareCsv to even make the universal driver work with that cmdlet. It seems the universal driver can not be added using a user-specified username/password but Import-HardwareCsv isn't using the `UseDefaultCredentials` switch on Add-Hardware in the event username/password are null or empty. So it requires you to provide a username/password value and if you do that with the universal driver it fails to add.
