### ISSUE TITLE
Setting StreamingMode property on the driver?

### ISSUE THREAD

**Issue by chriswiggins** [MilestoneSystemsInc/PowerShellSamples#20]
I'm trying to set the StreamingMode of a particular camera stream, but calling save on the various levels of the camera object does not seem to make this take effect.

I've verified my values are correct (by calling GetValueTypeInfoCollection) so I don't think it is that.

This is what I'm trying but with no luck:

```powershell
$cam = Get-Hardware -Name "Test" | Get-Camera
$cam.DeviceDriverSettingsFolder.DeviceDriverSettings[0].StreamChildItems[0].Properties.SetValue("StreamingMode", "RTPTCP")
$cam.DeviceDriverSettingsFolder.DeviceDriverSettings[0].Save()
$cam.DeviceDriverSettingsFolder.Save()
$cam.Save()
```

Any pointers or a better way to do this? I saw how you were getting this information in GetStreamingModeFromStream in the Private folder

**Comment by jhendricks123** [comment]
You'll need to save a reference to the settings object you're modifying so
that when you call Save() you're doing it on the same object that you
modified.

$driverSettings = $cam.DeviceDriverSettingsFolder.DeviceDriverSettings[0]

Do your thing to $driverSettings and call Save() on that object.


The following might be easier depending on the circumstances


 Set-CameraSetting -Stream -StreamNumber 0 -Name Setting key -Value Val

**Comment by chriswiggins** [comment]
Wow. `Get-CameraSetting` and `Set-CameraSetting` is exactly what I was after. Thanks @jhendricks123 !
