### ISSUE TITLE
History / Changelog

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#21]
Hello,

Is there a Changelog somewhere? I couldn't find it here or on https://www.powershellgallery.com/packages/MilestonePSTools/1.0.90

Thanks,
Philippe

**Comment by Silex** [comment]
Found it at "Package Details" on powershellgallery.

**Comment by chriswiggins** [comment]
@Silex Drop down package details and scroll down past the different CMDlets. You'll see a changelog
