### ISSUE TITLE
Delete rules

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#22]
Hello,

How do we delete rules? We need something like `Delete-ConfigurationItem`

``` powershell
$rule = Get-ConfigurationItem -Path /RuleFolder -ChildItems | Select-Object -First 1
$name = $rule | Get-ConfigurationItemProperty -Key 'Name'
Write-Output "Deleting rule $name"
$rule | Delete-ConfigurationItem
```

By the way the documentation for `Get-ConfigurationItemProperty` wrongly references `Get-PropertyValue`.

**Comment by jhendricks123** [comment]
Thanks for the tip on the incorrect cmdlet name in the documentation - that's fixed now for the next release.

I'm not sure there would be a clean way to make a single function called `Delete-ConfigurationItem` given the way the Configuration API works. To remove a rule for example, you would invoke the "RemoveRule" method on the RuleFolder ConfigurationItem. You would then get back an "InvokeInfo" object which has properties for you to fill out. You would fill in the Path value of the rule you want to delete in the property named "RemoveRulePath" , and then call `Invoke-Method` again on the InvokeInfo object that you just filled out.


Here's an example of a couple of functions for getting and removing rules. I haven't gotten around to building something for adding rules - creating them is a lot more complex than getting/removing them.

```powershell
function Get-Rule {
    [CmdletBinding()]
    param(
        [Parameter(ValueFromPipelineByPropertyName)]
        [Alias('DisplayName')]
        [string]
        $Name = '*'
    )

    process {
        $ruleFolder = Get-ConfigurationItem -Path /RuleFolder -Recurse
        $matchingRuleCount = 0
        Get-ConfigurationItem -Path /RuleFolder -ChildItems | Where-Object DisplayName -like $Name | Foreach-Object {
            $matchingRuleCount++
            $_
        }
        
        if ($matchingRuleCount -lt 1 -and ![wildcardpattern]::ContainsWildcardCharacters($Name)) {
            Write-Error "Rule not found matching name '$Name'"
        }        
    }
}

function Remove-Rule {
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory, ValueFromPipelineByPropertyName)]
        [Alias('DisplayName')]
        [string]
        $Name
    )

    process {
        $ruleFolder = Get-ConfigurationItem -Path /RuleFolder -Recurse
        $rules = [array]($ruleFolder.Children | Where-Object DisplayName -like $Name)
        if ($rules.Count -lt 1 -and ![wildcardpattern]::ContainsWildcardCharacters($Name)) {
            Write-Error "Rule not found matching name '$Name'"
            return
        }
        foreach ($rule in $rules) {
            if ($PSCmdlet.ShouldProcess($rule.DisplayName, 'Remove Rule')) {
                $invokeInfo = $ruleFolder | Invoke-Method -MethodId RemoveRule
                $invokeInfo | Set-ConfigurationItemProperty -Key 'RemoveRulePath' -Value $rule.Path
                $invokeInfo | Invoke-Method -MethodId RemoveRule
            }
        }
        
    }
}
```

**Comment by Silex** [comment]
Ah, alright thanks that's perfect for now 👍

**Comment by Silex** [comment]
Actually I found a bug on 2020R1:

``` powershell
(Get-ConfigurationItem -Path /RuleFolder -ChildItems).Length
2

(Get-ConfigurationItem -Path /RuleFolder -ChildItems).DisplayName
Default Record on Motion Rule
Default Goto Preset when PTZ is done Rule
```

I don't understand why it's limited to 2. I does not happen on 2020R3. Any idea?

**Comment by Silex** [comment]
Ok some rules were invalid (deleted recorders etc) but even after removing them it still refuses to list all rules.

**Comment by jhendricks123** [comment]
The ability to interact with rules is _very new_. Have a look at the [Configuration API documentation](https://doc.developer.milestonesys.com/html/index.html?base=gettingstarted/intro_configurationapi.html&tree=tree_4.html), specifically the "Rules configuration" section. There are limitations to the rules that can be represented via Configuration Item objects. In 2020 R1 it was extremely limited, and the SDK team has expanded the capabilities progressively in 2020 R2 and R3. The documentation provides a lot more insight about which rule actions and such are supported.

**Comment by Silex** [comment]
Okay, I just find it weird it only lists two rules out of ~8 (basically it cannot even list all the default ones).

Maybe I'll poke at it with the SDK to check if it reports the same thing.

**Comment by jhendricks123** [comment]
I'm 99% sure the reason only the couple rules show up in 2020 R1 is due to the limited scope of support for rules in the configuration api. And if it's somehow a bug, it would be a bug with the MIP SDK rather than MilestonePSTools. So I'll close this issue out today but if you have any questions/issues with manipulating rules from PowerShell feel free to post them as new issues. Thanks again for all your feedback 🥇
