### ISSUE TITLE
Question about Register-ScheduledJob Login

### ISSUE THREAD

**Issue by CarlOscar002** [MilestoneSystemsInc/PowerShellSamples#23]
Hi,

I have created a script that use the same login function as yours for the "schedueld vide export".
It´s all stored in an expanding string.
The only diffrent is that my script does something else than a video export.

It work perfectly when I am logged in to the server where the registered shedule is stored.
But if there is no user logged in on the server it doesn´t work.

A part of the script is to test a path and create it if it doesn´t exist, that part works. The only part that doesn´t work is to login to the management server. (It does work if I am logged in to the server)
Cause I can´t see any errors on the schedule task. And if I check the server logs I cannot see that the account have logged in to the management server. 

The account is a part of the Administrator group.

Do you have any suggestions?
Best regards,

**Comment by jhendricks123** [comment]
You know, I think I ran into the same issue a month or two ago where scheduled tasks created by Register-ScheduledJob were not working without the user being logged in. I forget exactly why - something to do with the way scheduled jobs work and how the actual script/job definition gets read from your user's appdata directory. I ended up creating a normal scheduled task to call a .ps1 script in that case.

I'll have to tinker with this and update that sample one way or another. Thanks for bringing this to my attention.
