### ISSUE TITLE
Question about setting 

### ISSUE THREAD

**Issue by jdd272** [MilestoneSystemsInc/PowerShellSamples#25]
Hello,
First of all thanks for this module, I use it to import loads of cameras into our MS system from CSV. I'm able to add it these in  correct group, automate settings & ACLs etc ...

The only 2 things I've not been able to do so far are:
- Once I set the Playback security attribute to "true" for a role on a device, I need to restrict the playback time to 15 minutes
- Same when I set ACTIVATE_PTZ_PRESET & PTZ_CONTROL to "true" I would like set the PTZ Priority parameter as well

Is there a way to accomplish this with MilestonePSTools ? And if yes how ? Thanks a lot

**Comment by jhendricks123** [comment]
I don't think we have access through MIP SDK to specify time properties associated with permissions but I *think* I heard this will be available later this year.

@Tarterman was this one of the potential MIP SDK features for R2 that you mentioned this week? I'm out of the office next week. So I'll follow up on the week of the 2nd in case Jared doesn't have a chance to drop in here.

**Comment by Tarterman** [comment]
There are a few things planned for configuration in R2 but the time properties associated with permissions is currently not one of them.

**Comment by jdd272** [comment]
Alright, thank you both for your answers
