### ISSUE TITLE
How to read/write settings?

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#26]
Is there a way to progammatically configure the audit logs retention?

If not with the pstools, maybe with the SDK?

And if none of that, I already found `[dbo].[SystemSettings]` but well, not a fan of hitting the DB :wink:

**Comment by jhendricks123** [comment]
I believe we're expecting to be able to access those settings through the configuration API in the 2021 R2 release coming next month. Until then you're stuck manipulating the SQL database. Sorry!

When 2021 R2 comes out, the new configuration API features will require a server-side update to 2021 R2 as it's not enough just to upgrade to the latest MilestonePSTools / MIP SDK.

**Comment by Silex** [comment]
So until a full server upgrade to 2021 R2 it's not possible. Alright thanks!

**Comment by Silex** [comment]
@jhendricks123 I noticed something weird:

``` powershell
Import-Module SQLPS
Invoke-Sqlcmd -Query "select * from [Surveillance].[dbo].[SystemSettings] where Name like 'Log%'" -ServerInstance $server

LastModified        Name                                Setting
------------        ----                                -------
19.12.2019 15:57:16 LogAuditEnableUserAccessLogging     True   
05.12.2019 10:02:38 LogAuditMaxLogEntries               50000  
19.12.2019 15:57:16 LogAuditPlaybackFramesBeforeLogging 1      
21.09.2021 09:41:44 LogAuditPlaybackWindowSizeInSec     30     
05.12.2019 10:02:38 LogAuditTimeToKeepLogEntries        2592000
05.12.2019 10:02:38 LogRuleEnabled                      true   
05.12.2019 10:02:38 LogRuleMaxLogEntries                50000  
05.12.2019 10:02:38 LogRuleTimeToKeepLogEntries         2592000
19.12.2019 15:57:16 LogSystemCanUseLevels               true   
19.12.2019 15:57:16 LogSystemLevel                      1      
05.12.2019 10:02:38 LogSystemMaxLogEntries              50000  
05.12.2019 10:02:38 LogSystemTimeToKeepLogEntries       2592000
```

If I modify `LogAuditPlaybackWindowSizeInSec` in the interface, it's correctly modified in the DB. If I modify `LogAuditTimeToKeepLogEntries`, the DB always stays at 2592000, which is 30 days (* 24 * 3600).

I tried looking into other tables and in `%programdata%\Milestone` inside the XML files, but couldn't find where this setting is saved.

Any idea? This is on 2021 R1.

**Comment by jhendricks123** [comment]
I think the retention settings got moved to SurveillanceLogserverV2.LogServer.RetentionConfiguration.

**Comment by Silex** [comment]
Ah good idea I forgot to check the 2nd database. I'll figure it out, thanks!
