### ISSUE TITLE
Execute an Export-HardwareCsv

### ISSUE THREAD

**Issue by ScottK-888** [MilestoneSystemsInc/PowerShellSamples#29]
Hi, i'm very new to MilestonePStools and PowerShell in general and would appreciate some guidance. When trying to use MilestonePSTools to Export- HardwareCsv i'm asked to supply InputObjects. see below:

cmdlet Export-HardwareCsv at command pipeline position 1

Supply values for the following parameters:

InputObject[0]:

I'm not sure how to supply this. Could anyone point me in the right direction. 

My hope is to create a CSV that I can then import to an additional parallel recording server for which will record a 2nd stream from the same cameras.

Thanks for reading

**Comment by jhendricks123** [comment]
Closing this idle issue. Feel free to re-open if the same issues persist, or open a new bug if the situation changes. Your issue reports and feedback are greatly appreciated!

**Comment by ScottK-888** [comment]
Hi. I notice that when I view the .csv created from an Export-VMShardware it doesn't give me the device MAC address. How can I edit the command to include this? Thank you
