### ISSUE TITLE
Question - Example of CameraReport with Snapshot

### ISSUE THREAD

**Issue by CarlOscar002** [MilestoneSystemsInc/PowerShellSamples#30]
Hi,

Not an issue, but is it possbile that you (Josh?) could share an example with get-camerareport with included Snapshot?
I use a module so you can pipe the export to an Excel-file, so it should work.
But I am stuck, cannot quite convert the system.image.. 

Best regards,

**Comment by CarlOscar002** [comment]
Hi Josh,

Perfect, thank you. I will have look at it.
You have done a great work with MilestonePSTools!

Thanks for the help and fast respond!

Best regards,

**Comment by jhendricks123** [comment]
No problem Carl, cheers!
