### ISSUE TITLE
Change Milestone Camera Name, Hardware Name & Camera Shortcut from a CSV File

### ISSUE THREAD

**Issue by cfedeli** [MilestoneSystemsInc/PowerShellSamples#33]
Hello, 
I have been updating camera names from CSV files but would like to know if its possible to also change the hardware name and camera shortcut at the same time, I have tried a few hardware reports and have edited the same script that I use for camera name imports but I cannot seem to get it to work.

Any help would be greatly appreciated, Let me know if there is any information that I can provide to assist, Thank you. 

Chris

**Comment by jhendricks123** [comment]
Closing this idle issue. Feel free to re-open if the same issues persist, or open a new bug if the situation changes. Your issue reports and feedback are greatly appreciated!
