### ISSUE TITLE
Possible to get the timestamp of PasswordLastChanged?

### ISSUE THREAD

**Issue by chriswiggins** [MilestoneSystemsInc/PowerShellSamples#35]
Team,

Is it possible to get the value that a password was last changed for a hardware device, similar to what you see in the Management Client?

I can't seem to find a way to do this in the SDK

**Comment by jhendricks123** [comment]
Hi Chris,

It doesn't look like any of the bulk password management components are exposed in MIP SDK yet. I looked at the strongly typed hardware objects, the generic "configurationitem" objects through `Get-ConfigurationItem`, looked for something useful in the IServerCommandService through `Get-IServerCommandService`, and through the unsupported VMO client interface.

We can only get/set the Milestone copy of the password it seems =/

**Comment by joshooaj** [comment]
Closing this issue as there doesn't appear to be anything we can do from PowerShell without breaking the "no SQL rule". I've passed a request on to the MIP SDK team to consider adding access to the bulk password management feature.
