### ISSUE TITLE
Module does not contain command to get rules from Milestone system

### ISSUE THREAD

**Issue by ristopii** [MilestoneSystemsInc/PowerShellSamples#4]
I cannot find powershell command to get all rules and save to other Milestone management server.
I have purpose to get rules migrated to one management server to another. 
I created issue here, because i am not able to post it to this site. https://mymilestone.force.com/developer/s/article/How-To-Use-MilestonePSTools-PowerShell-Module

**Comment by jhendricks123** [comment]
Hi Ristopii,

The MIP SDK has limited support for working with rules which was just released in 2020 R1. The features available right now are accessible from MilestonePSTools using the cmdlets Get-ConfigurationItem, Set-ConfigurationItem, and Invoke-Method cmdlets. The MIP SDK documentation for Configuration API including the new rules functioality can be found here: https://doc.developer.milestonesys.com/html/index.html?base=gettingstarted/intro_configurationapi.html&tree=tree_4.html

I haven't had an opportunity to play with the new rules functionality but if you successfully use PowerShell to copy some of your rules from one site to another, I'm sure the community would appreciate a sample if you're willing/able to share.

Unfortunately right now you won't be able to copy all rules from site to site as only a limited number of types of rules are accessible. And unless the rules are associated with the "All cameras" group, you'll need to account for different device group ID's. For example, if you have a rule based on motion started for a camera group called "Parking", that group will have a different unique identifier on two different sites even if the device group has the same name.

**Comment by ristopii** [comment]
Does this MilestonePSTools have ability to get this "/RuleFolder" configuration items or do you example how to get these?
I have installed latest MilestonePSTools version 1.0.72 and MipSdkRedist module.

PS C:\Windows\system32> Get-ConfigurationItem -Path /RuleFolder
Get-ConfigurationItem : The server doesn't support the specified path
Parameter name: path
At line:1 char:1
+ Get-ConfigurationItem -Path /RuleFolder
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ConfigurationItem], FaultException`1
    + FullyQualifiedErrorId : System.ServiceModel.FaultException`1[[VideoOS.ConfigurationApi.ClientService.ArgumentExceptionFault, VideoOS.Platform, Version=1.0.0.0, Culture=neutral, Publ 
   icKeyToken=bc60fba4a7969f89]],MilestonePSTools.ConfigApiCommands.GetConfigurationItem

**Comment by jhendricks123** [comment]
Limited access to rules via MIP SDK was added in 2020 R1, so even though you're using the 2020 R1 version of MIP SDK with MilestonePSTools 1.0.72, the server is still 2019 R3 and doesn't support the /RuleFolder path.

Once you upgrade the Management Server to 2020 R1, you should see some results in that query.

**Comment by jhendricks123** [comment]
Here are the property keys/values for the default record on motion rule output from the Get-ConfigurationItem cmdlet for reference

```powershell
PS C:\> Get-ConfigurationItem -Path /RuleFolder -ChildItems | Select -First 1 | % { $_.Properties | Select Key, Value }                                                                                                                      
Key                            Value
---                            -----
Id                             3307C095-A170-49D3-AB11-1BAF8783ACB9
Name                           Default Record on Motion Rule
Description
StartRuleType                  Event
StopRuleType                   Event
StartEventGroup                DevicePredefined
StartEventType                 6eb95dd6-7ccc-4bce-99f8-af0d0b582d77
StartEventSources              CameraGroup[0e1b0ad3-f67c-4d5f-b792-4bd6c3cf52f8]
StopEventGroup                 DevicePredefined
StopEventType                  6f55a7a7-d21c-4629-ac18-af1975e395a2
StopEventSources               CameraGroup[0e1b0ad3-f67c-4d5f-b792-4bd6c3cf52f8]
StartActions                   StartRecording
Start.StartRecording.Delay     -3
Start.StartRecording.DeviceIds Camera[00000000-0000-0000-0000-000000000000]
StopActions                    StopRecording
Stop.StopRecording.Delay       3
Stop.StopRecording.DeviceIds   Camera[00000000-0000-0000-0000-000000000000]
```
