### ISSUE TITLE
MilestonePSTools not working on server 2012 R2

### ISSUE THREAD

**Issue by Louisdentic** [MilestoneSystemsInc/PowerShellSamples#41]
Hi,

I try to work MilestonePSTools version 21.2.2 on this server 2012 R2 and it's dosen't work. I follow the same step by step on my 2019 server it's working fine.
Normally the prerequisites are good.

Import looks good just I have an error : 
_

> Unable to verify .NET Framework 4.7 version because it is not in the list of allowed versions

_ 
(I want to clarify that the net framework is installed)

I have a same error on server 2019 but it's work when i use this cmd Set-MobileServerCertificate
![image](https://user-images.githubusercontent.com/98382871/150936428-163bff26-bf24-492c-bf0f-716bced02845.png)

When I launch the cmd I had this error 
![image](https://user-images.githubusercontent.com/98382871/150935779-a6ebb2a5-c741-4eca-a240-d47afe927414.png)

I hope to have been clear
Thanks for your help

**Comment by joshooaj** [comment]
Thanks for the detailed issue report! Hopefully I'll get the opportunity to spin up a 2012 server for test sometime this week or next.

In full transparency, while I do want this to work on Server 2012, especially if the fix is easy, the OS is nearly at the end of it's Microsoft extended support service life and thus will likely be unsupported by Milestone soon as well. Since the module relies heavily on the Milestone MIP SDK, there's a chance the problem is related to a compatibility issue between the SDK and 2012. If that's true, it's unlikely I can do anything to solve the problem.

I heard some news about recent Windows updates causing issues on Server 2012 so I'll look into whether that could be the case here. Let me know if you have any other insights to help me narrow it down. Thanks again for the report!

**Comment by joshooaj** [comment]
I launched a Server 2012 R2 instance on AWS and...

- Installed Windows Management Framework 5.1
- Installed MilestonePSTools v21.2.5 from PowerShell Gallery
- Successfully logged in to an XProtect Corporate 2021 R2 system on another machine
- Noticed that `Get-VmsCamera` was not found
- Upon further inspection, *none* of the functions exported by MilestonePSTools were found. The only commands available are the cmdlets built in C# and exported as cmdlets.

Here's a comparison of Server 2012 (in the background) and Windows 10 in the foreground. A big chunk of the commands in the module are simply not being loaded in Windows Server 2012 R2. I'm still looking into why that is. The warning about .NET 4.7 is a pretty normal message, apparently PowerShell just doesn't validate that but I leave the .NET version in the psd1 file to be explicit about what version of .NET was used.

![Screenshot of two PowerShell windows](https://user-images.githubusercontent.com/7669972/153038352-55521e29-8ec4-4e1f-a4b6-c6b4743fa254.png)

**Comment by joshooaj** [comment]
Okay, figured it out. I'm not sure why there's a behavior difference between Server 2012 R2 and Server 2019 but the issue on 2012 R2 is that at the end of MilestonePSTools.psm1 we're calling `Export-ModuleMember` with a list of cmdlets to export from  MilestonePSTools.dll and we need to *also* export the functions. Until I release the next MilestonePSTools version to PowerShell Gallery, you can modify the MilestonePSTools.psm1 file to change `Export-ModuleMember` at the bottom to...

```powershell
Export-ModuleMember -Cmdlet * -Alias * -Function *
```

The module is signed, so you'll need to delete the authenticode signature from the bottom of the psm1 file when you make the change. Once you do that, I think you'll be able to import and use the module just fine on Server 2012 R2.

I'd recommend against using Set-MobileServerCertificate though. That was written before the command-line interface was added to the Server Configurator tool included with the VMS. The [Set-XProtectCertificate](https://www.milestonepstools.com/Functions/Set-XProtectCertificate/) command is a better choice - it uses [Invoke-ServerConfigurator](https://www.milestonepstools.com/Functions/Invoke-ServerConfigurator/) under the covers and does a little more work for you in terms of making sure the certificate's private key is accessible using the service account name you provide, and removing the old certificate from the certificate store if you don't want it there anymore.
