### ISSUE TITLE
Problem with Import-VmsHardware

### ISSUE THREAD

**Issue by tav71** [MilestoneSystemsInc/PowerShellSamples#42]
Hi, 
I am facing some issues with Import-VmsHardware. After executing the command with a csv file created with the -SaveTemplate option, it did import the list of cameras into Milestone Corporate 2020 R3, however, the camera devices under the respective Hardware are not Enabled. And the funny thing is the Microphone device which was configured to be Enabled in the csv is properly Enabled.

I did also tried Set-VmsCamera to Enable the camera device but failed. The command statement as below:
GET-HARDWARE -Name "*Q3515*" | Get-VMSCamera -Channel (0) -Verbose | Set-VmsCamera -Enabled $true

After playing around with the commands, I found that Get-VMSCamera do not list any camera channel which is currently disabled and hence Set-VmsCamera will not get a list of disabled camera device to enable them.

**Comment by joshooaj** [comment]
Hi @tav71,

Yeah, Import-VmsHardware needs some love. It's nowhere near as robust as I'd thought/hoped so I'll be revisiting Start-VmsHardwareScan, Add-VmsHardware, and Import-VmsHardware soon. I like the flexibility Import-VmsHardware has for doing simple imports, as well as larger imports with customized device names/states, but it has a couple of draw backs...

1. Currently it relies on a successful scan using Start-VmsHardwareScan, even if you provided the driver number in the CSV. There's no point in doing that - we should just go straight to adding the hardware and skip the scan when we have all the information needed to add the camera already. Some camera drivers/models simply don't respond well to a hardware scan, even further reason to change that behavior.
2. The camera is sometimes not enabled for some reason. I hadn't seen this behavior until after release of the new function and I haven't dug into why it's happening yet.

Can you share the camera make/model you used? When we revisit Import-VmsHardware I want to try to test with some of the same devices people are using and observing issues with in the field.

With regard to the Get-VmsCamera command, it now behaves similar to the default Configuration API behavior we'll be seeing with the REST api where by default, only enabled devices are returned. If you wanted to find **all** disabled cameras and enable them, you could do...

```powershell
# This option, where we don't enumerate through hardware first, requires 2020 R2 or later
Get-VmsCamera -EnableFilter Disabled | Set-VmsCamera -Enabled $true -Verbose

# This option is compatible with all VMS versions
Get-Hardware | Get-VmsCamera -EnableFilter Disabled | Set-VmsCamera -Enabled $true -Verbose
```

**Comment by tav71** [comment]
Hi Joshooaj,

The camera model I am using is Axis Q3515 LVE. 

I tried the -EnableFilter option and it works fine. Thanks.

**Comment by joshooaj** [comment]
It looks like the update to Get-VmsCamera (formerly Get-Camera) and the default behavior to return enabled cameras only by default is at fault here.

When adding new hardware, the new hardware starts out disabled, as do all child devices. The Import-VmsHardware command needs to enable the specified channels but we need to include "-EnableFilter All" in the call to Get-VmsCamera.

This will be fixed in the next update. Meanwhile, if you install a previous version of MilestonePSTools before the introduction of Get-VmsCamera, it should work better. I think 21.2.2 should work.

**Comment by Silex** [comment]
Ah yes please, improve `Import-VmsHardware` :sweat_smile:

The fix of adding `-EnableFilter All` works (the camera is enabled with the proper name) but there's a biger design problem: you cannot export/import a hardware that has multiple cameras with different names.

In my own tool I solved this by using a CSV that was camera-oriented with a column "HardwareIp" and "CameraChannel", on the first line encountered it adds the hardware and configure the proper camera channel 0 and on the second line it *finds* the existing hardware and configures the proper camera channel 1.

**Comment by joshooaj** [comment]
I believe `Export-VmsHardware` and `Import-VmsHardware` do enable working with devices with multiple channels. Here's an excerpt from the docs:

```text
- CameraName, MicrophoneName, SpeakerName, MetadataName, InputName, OutputName If any device names are
  provided, then the default value will be replaced with the values in the csv. Multiple values can be
  provided, so you can name all 4 cameras on a 4-channel device by delimiting each value with a semicolon (;)
  symbol. The first camera, which is considered channel 0, would be named by the first value, and camera 2, which is
  considered channel 1, would be named by the value after the first semicolon.
```

**Comment by Silex** [comment]
It would be nice if `Import-CSVHardware` also *configured* the hardware/devices if it finds them already set up on the recording server.

**Comment by Silex** [comment]
`Import-VMSHardware` is also broken if you specify another recording server, because it wrongly detects 'WARNING: One or more scanned hardware already exist on the target recording server. These entries will be skipped.'

In the code that corresponds to `$HardwareScan.MacAddressExistsLocal` and I double checked no other device have the same MAC address on that recorder, probably it took the addresses from the other recording server.

**Comment by Silex** [comment]
Oh, I find `Added using PowerShell at 05/03/2022 17:40:41` in the hardware description very annoying :sweat_smile:
