### ISSUE TITLE
Rename All cameras in 2020 R2

### ISSUE THREAD

**Issue by hamzasa1** [MilestoneSystemsInc/PowerShellSamples#44]
Hello, 

May you please assist with PStool command to rename all cameras only via CVs file. i tried with below- but sees the get-camera command is not recognized, and nothing is being export.

```powershell
# Export some camera information to CSV
$list = New-Object System.Collections.Generic.List[pscustomobject]
foreach ($rec in Get-RecordingServer) {
    foreach ($hw in $rec | Get-Hardware) {
        foreach ($cam in $hw | Get-Camera | Sort-Object Channel) {
            $driver = $hw | Get-HardwareDriver
            $mac = ($hw | Get-HardwareSetting).MacAddress
        
            $list.Add([pscustomobject]@{
                CameraName = $cam.Name
                Channel = $cam.Channel
                CameraId = $cam.Id
                HardwareName = $hw.Name
                Address = $hw.Address
                MAC = $mac
                Driver = $driver.DisplayName
                Model = $hw.Model
                Recorder = $rec.Name
            })
        }
    }
}
$list | Export-Csv .\cameras.csv -NoTypeInformation

# Import CSV, locate hardware by ID, and update Name based on the value in CSV file
$rows = Import-Csv .\cameras.csv
foreach ($row in $rows) {
    $cam = Get-Camera -Id $row.CameraId
    if ($null -eq $cam) {
        Write-Warning "Could not find hardware '$($row.HardwareName)' with ID '$($row.HardwareId)'"
        continue
    }
    $cam.Name = $row.CameraName
    $cam.Save()
}
``` 

Thanking you in advance

**Comment by joshooaj** [comment]
Hi @hamzasa1,

The script works for me, but the `Get-Camera` cmdlet has been renamed to `Get-VmsCamera` - we are slowly going through and prefixing older cmdlets with "Vms" to avoid cmdlet name collisions with other modules. There's an alias for `Get-Camera` pointing to `Get-VmsCamera` but maybe that alias isn't working for you?

Try changing the command name to `Get-VmsCamera` and see how it goes. MilestonePSTools v21.2.7 was published today as well - if you want to do any work with views/viewgroups you should check it out!

Cheers,

Josh

**Comment by subbuun** [comment]
Thanks. I was able to export the camera to CSV. Can you please help me with the command to import it after renaming the camera and hardware.

**Comment by subbuun** [comment]
Thanks Jared


I had a look at the Import-VmsHardware and tried it. But look like it is trying to add the device instead of renaming the camera.
Can you please help me with the exact command to modify the existing camera name ?

Also I had a look at the Import Hardware From Excel and tried it. But it provided more sheet where i have to modify the names in multiple sheets. Is there a way i can get the list of cameras on one sheet and rename it ?

________________________________

**Comment by Tarterman** [comment]
I forgot that Import-VmsHardware was strictly for importing and couldn't update existing items.

Using the ImportVmsHardwareExcel module, you can do the following:

```
Export-VmsHardwareExcel -Path "C:\tmp\hardware.xlsx" # Change the path as needed
```

Open the Excel file.  If you want to change the Hardware name, do that on the "Hardware" tab.  If you want to change the camera name, you only need to change it on the "Cameras" tab.  Once the changes have been made, running the following:

```
Import-VmsHardwareExcel -Path "C:\tmp\hardware.xlsx" -UpdateExisting
```

I also just ran across this sample that Josh put together that might be a better option since it just does what you are asking for.

[Set-MilestoneNames](https://github.com/MilestoneSystemsInc/PowerShellSamples/blob/main/Samples/Set-MilestoneNames.ps1)

**Comment by subbuun** [comment]
Great Thanks ! The Set-MilestoneNames<https://github.com/MilestoneSystemsInc/PowerShellSamples/blob/main/Samples/Set-MilestoneNames.ps1> is working fine for me.
________________________________

**Comment by subbuun** [comment]
![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/141190871/20eb8f82-843f-4aee-a463-2fcddd3cf087)

I am trying to use the Group-CamerasByModel.ps1 module, it is creating the groups, but it is also throwing the error as in the attached


![Group-CamerasByModel Error](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/141190871/c5223eca-2775-494f-b13c-d8d0947bebed)

**Comment by Tarterman** [comment]
It looks like there is a bug related to structure of newer cmdlets that replaced older ones.  We'll have to look into it but I verified on my system that it does seem to be properly creating the groups, so that is good.

**Comment by Tarterman** [comment]
The Group-CamerasByModel has been updated to fix the bug.  It should work properly without throwing the error now.

**Comment by subbuun** [comment]
Great thanks !!

**Comment by subbuun** [comment]
Can you please help me with the command to Disable all streams except for the first one ?

And move all the disabled cameras to a separate Camera group ?

**Comment by Tarterman** [comment]
To clarify, do you mean disable all channels except for the first one or streams?

These are channels:
![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/80aa3f54-a71d-444a-85a7-14d7a77b9d25)

These are streams:
![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/cbb20ec1-e467-473d-a27d-a3e1349777b1)

Also, why do you want to move disabled cameras to a camera group?  Typically, disabled cameras aren't in any camera group?

**Comment by subbuun** [comment]
Thanks Jared.

Yes disable all channels except the first one as in the first snap , not the streams.

[image]<https://user-images.githubusercontent.com/42384254/258888977-80aa3f54-a71d-444a-85a7-14d7a77b9d25.png>


________________________________

**Comment by Tarterman** [comment]
As an example, you could do something like this:

```
foreach ($hw in Get-VmsHardware)
{
   foreach ($cam in $hw.CameraFolder.Cameras)
   {
      if ($cam.Channel -gt 0)
      {
         $cam.Enabled = $false
         $cam.Save()
      }
   }
}
```
That will look at each hardware and get the cameras/channels for that hardware and then it will look at each camera/channel and if it is not channel 0 (which is the first channel), it will disable it.
