### ISSUE TITLE
Get-Snapshots not getting Live Snapshots when specified

### ISSUE THREAD

**Issue by Tarterman** [MilestoneSystemsInc/PowerShellSamples#47]
Getting live snapshots is getting a snapshot of the last recorded video sequence instead of getting a live snapshot.  I discovered this because I was getting a snapshot on a defined interval and noticing that it wasn't saving a new snapshot on that interval.  It doesn't matter what camera I choose.  It also doesn't matter if I'm saving the snapshot or just doing something like this and just looking at the BeginTime and EndTime.

`$c = Select-Camera`
`$c | Get-Snapshot -Live`

**Comment by joshooaj** [comment]
I think the problem has been solved by changing the default value of `SendInitialImage` on the `VideoOS.Platform.Live.JPEGLiveSource` class from `true` to `false`. The default value can result in really old "live" images which can improve a live operator experience when changing views, so they get an initial image to look at as the view loads, but isn't very useful when you're trying to get actual live images.
