### ISSUE TITLE
Fix typo in Import-VmsHardware

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#49]
```
The DriverFamily column provides an easy shortcut to select all driver numbers under the group in a similar fashion to the Add Hardware dialog in Management Client. The valid DriverFamily values can be found by running `Get-RecordingServer -Name JMT-XPCO | Get-HardwareDriver | Select-Object -ExpandProperty GroupName -Unique`
```

You'd replace `-Name JMT-XPCO` with ` | Select-Object -First 1` :wink:

**Comment by joshooaj** [comment]
I don't know if I'll have a chance to dig into the issues you've reported this week but I want to say THANK YOU for all the feedback/issues/suggestions! I __really__ appreciate you taking the time to share it all here ♥

**Comment by Silex** [comment]
Thank **you** for doing this! I know it's probably not easy to convince your company to make these tools but they are very useful.

About this issue, I know open source is always a bit of an issue but maybe you could make a repo out of https://www.milestonepstools.com so people could fork/patch the documentation (and maybe the code one day :stuck_out_tongue_winking_eye:)

**Comment by Silex** [comment]
`Export-VmsHardware` appends to the destination CSV, it'd ask for confirmation to overwrite IMHO.

**Comment by joshooaj** [comment]
Thanks @Silex, for the next release I've corrected the typo and added an `-Append` switch to `Export-HardwareCsv` and I just pass that value on to the `Export-Csv` cmdlet. So by default it will overwrite which is the normal behavior when exporting to CSV, and in the off chance you want to append, you can add the switch.
