### ISSUE TITLE
Problem with Update-hardware function

### ISSUE THREAD

**Issue by ChrisM-OK** [MilestoneSystemsInc/PowerShellSamples#55]
Hi Josh,
As per previous emails, you made some amendments to the Update-hardware function to allow the modification of Passwords to be included when using a CSV file to import batches of data.  I also have another issue with the function and wonder if you can make another amendment, or advise me of another way do to this,.

![ChangedName](https://user-images.githubusercontent.com/40069521/171107112-124eab15-37c9-49d2-a87e-51f9a4503a94.JPG)

 I have used the get-hardware function to create a .csv file of my cameras and then made a change to the name of the camera. I have then used the Update-hardware function to apply that .csv file to my recorder.  As per the highlight in the enclosed snip, I have changed the camera name to 'Trim Cam220121' which the Update-hardware has brought in fine, however all of the elements underneath that still remain as per the existing name 'Trim Cam121'.
The same issue is seen when changing the name in the GUI,. 

Is it possible to have some way to change this nested information to match the hardware name?

Thanks a lot,
Chris.

P.S. great work on this project and long may it continue.

**Comment by joshooaj** [comment]
Hi Chris,

Do you have the original Update-Hardware function handy? I don't recall it and it's not a function in MilestonePSTools or these samples.

Generically, if you wanted to rename all child devices of a hardware object to a format like "HardwareName - DeviceType Channel#", you could do...

```powershell
function Reset-AllDeviceNames {
    <#
    .SYNOPSIS
    Resets all device names to the default pattern "HardwareName - DeviceType ChannelNumber".
    
    .DESCRIPTION
    The default naming convention for the devices associated with a "hardware"
    object in Milestone (typically a physical camera) is something like
    "MyCamera (192.168.1.101) - Camera 1" where "MyCamera (192.168.1.101)" is
    the name of the hardware in Management Client..

    This function uses the current hardware name, and applies this naming
    convention to all cameras. Use it wisely.

    .PARAMETER RecordingServer
    Optionally provide one or more recording servers to limit the scope of
    device names to be reset.

    .EXAMPLE
    Reset-AllDeviceNames -WhatIf

    Shows what would happen if the function was called without the -WhatIf switch.

    .EXAMPLE
    $recorder = Get-RecordingServer | Out-GridView -OutputMode Single
    $recorder | Reset-AllDeviceNames -WhatIf

    Prompts you to select one recording server in a grid view dialog, then shows
    all the renames that would occur if the -WhatIf switch was not present.
    #>
    [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
    param(
        [Parameter(ValueFromPipeline, Position = 0)]
        [VideoOS.Platform.ConfigurationItems.RecordingServer[]]
        $RecordingServer
    )

    process {
        if ($null -eq $RecordingServer) {
            $RecordingServer = Get-RecordingServer
        }

        $nameTemplate = '{0} - {1} {2}'
        foreach ($recorder in Get-RecordingServer) {
            foreach ($hardware in $recorder | Get-Hardware) {
                $devices = @($hardware | Get-VmsCamera -EnableFilter All) + @($hardware | Get-Microphone) + @($hardware | Get-Speaker) + @($hardware | Get-Metadata) + @($hardware | Get-Input) + @($hardware | Get-Output)
                foreach ($device in $devices) {
                    $deviceType = [VideoOS.Platform.Proxy.ConfigApi.ConfigurationItemPath]::new($device.Path).ItemType.Replace('Event', '')
                    $channel = $device.Channel + 1
                    $newName = $nameTemplate -f $hardware.Name, $deviceType, $channel
                    if ($device.Name -cne $newName -and $PSCmdlet.ShouldProcess("Recording Server '$($recorder.Name)'", "Rename '$($device.Name)' to '$($newName)'")) {
                        $device.Name = $newName
                        $device.Save()
                    }
                }
            }
            $recorder.ClearChildrenCache()
        }
    }
}

```

**Comment by joshooaj** [comment]
Hi @ChrisM-OK,

I'm closing this issue today and feel free to comment or open a new issue as needed :)

Cheers,

Josh
