### ISSUE TITLE
Get-VmoClient not working anymore

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#59]
Hello,

```
PS C:\Users\ext-adm-pva> Connect-ManagementServer
PS C:\Users\ext-adm-pva> Get-VmoClient
Get-VmoClient : Method not found: 'Void
VideoOS.Management.VmoClient.VmoClient..ctor(VideoOS.Management.VmoClient.ServerConnection)'.
At line:1 char:1
+ Get-VmoClient
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VmoClient], MissingMethodException
    + FullyQualifiedErrorId : System.MissingMethodException,MilestonePSTools.ConfigApiCommands.GetVmoClient
```

This breaks https://www.powershellgallery.com/packages/MilestonePSTools.Security in `Import-Role`

**Comment by Silex** [comment]
This also broke https://www.powershellgallery.com/packages/MilestonePSTools.ClientProfiles, but this package is even worse because it straight out does not work out of the box, the packaging looks wrong.

**Comment by Silex** [comment]
Ok, I found out the only thing that works is installing version MilestonePSTools `1.0.90` and MilestonePSTools.Security `0.1.448774`.

I'll let the issue open so you have a chance to fix this 😉

**Comment by Silex** [comment]
... and if you want to use `Milestonepstools.ClientProfiles` make sure to remove the `-alpha` from the folder name 😅

**Comment by joshooaj** [comment]
My goal for MilestonePSTools is to be able to publish the full source on the official MilestoneSys github account, and be able to accept pull requests from the community there. In preparation for that I removed any components of the module that made use of unsupported API's like VmoClient and ServerProxyService. These are API's used internally by MIP SDK but not intended for use by our customers and technology partners, so to have the best chance of getting approval to publish the module source for the community, I removed those bits.

The VmoClient can be useful from time to time so if you need it, you can use this [Get-VmoClient gist](https://gist.github.com/joshooaj/b38e9e9be048bf5b197e2b58d5f70b8f).

The MilestonePSTools.* modules are... not great. I actually had forgotten they were there so thank you for the reminder! I'm finally combing through the issues here today (thank you again for posting them, and also for your patience!) and I'll have to come back to the ClientProfiles and Security "sub-modules" and decide what to do with them later. My original thought was that this "sub-module" concept could be used to provide more "opinionated" implementations like importing/exporting resources where some assumptions are made for you about the format of the input/output files or default values. The import/export of roles for example I think uses JSON to document the roles, properties, members, and overall security permissions. I still think this is a good idea - it helps keep the root module "clean" and free of too many assumptions. But I'd like to stick to having any modules published to psgallery being fully "supportable" by using only the API's Milestone supports for use by our customers, and I think both of those modules will need to be rebuilt to use supported interfaces.

I'll close this issue today and make myself a reminder to tackle those sub-modules later. If there's anything broken or missing in the root module preventing you from solving a problem related to client profiles or security, let me know how I can help in a new issue. There are no Smart Client profile cmdlets _yet_, but on VMS versions with support for them in configuration api you can get to them using `(Get-VmsManagementServer).ClientProfileFolder.ClientProfiles`

If you need more detail about the value types for the properties in each of the client profile tabs, you'll have to switch to the generic configuration api objects as the strongly-typed objects don't have the "ValueTypeInfos" describing the enum values and whatnot. Here's some pwsh to extract all the profiles and their settings into rows for example...

```powershell
foreach ($clientProfile in Get-ConfigurationItem /ClientProfileFolder -ChildItems) {
    $profileName = $clientProfile.Properties | Where-Object Key -eq 'Name' | Select-Object -ExpandProperty Value
    foreach ($tab in $clientProfile.Children) {
        $settings = @{}
        $tab.Properties | Foreach-Object { $settings[$_.Key] = $_ }
        foreach ($property in $tab.Properties | Where-Object Key -notlike '*Locked') {
            $locked = $settings[('{0}{1}' -f $property.Key, 'Locked')].Value
            $options = ''
            if ($property.ValueTypeInfos.Count) {
                $options = [string]::Join('|', $property.ValueTypeInfos.Value)
            }
            [pscustomobject]@{
                Profile = $profileName
                Tab     = $tab.DisplayName
                Setting = $property.DisplayName
                Key     = $property.Key
                Value   = $property.Value
                Locked  = $locked
                Options = $options
            }
        }
    }
}
```

**Comment by Silex** [comment]
Thanks for the feedback, I think your plan is sound. I wanted to use these modules to gain some time but you're right, I should be able to code the same with the main module.

If I was you I'd maybe update the README of these submodules with the fact that they only work right now with version `1.0.90`, or even remove them completely for the time being.
