### ISSUE TITLE
Get-VmsCameraReport error

### ISSUE THREAD

**Issue by travismassey1854** [MilestoneSystemsInc/PowerShellSamples#60]
Using the following:
Win Server 2016 DataCenter
Milestone management server 2016R3
PS Tools 22.1.0

Running command Get-VmsCameraReport is coming back with the below error.     Is this due to version of Milestone and PSTools or, is there a step that I've missed?   Thank you for your assistance
![PSTool error](https://user-images.githubusercontent.com/108106115/175441582-574ca8f4-4c1e-4377-84d1-95e559996351.png)

**Comment by joshooaj** [comment]
Hi @travismassey1854,

It would seem that your Milestone environment might be in an unexpected state. What is happening is the `Get-VmsCameraReport` cmdlet is getting all your recording servers, and retrieving information for every camera on all servers. At least one of those recording servers is not providing `Get-VmsCameraReport` with a URL/URI like "http://myrecorder:7563". What does it look like when you run the following command?

```powershell
Get-RecordingServer | Select-Object Name, WebServerUri, @{N='FQID.ServerId.URI'; E={[VideoOS.Platform.Configuration]::Instance.GetItem($_.Id, [VideoOS.Platform.Kind]::Server).FQID.ServerId.Uri}}
```

You should see something like...

```plaintext
Name       WebServerUri            FQID.ServerId.URI
----       ------------            ---
MyRecorder http://myrecorder:7563/ http://myrecorder:7563/
```

If the `FQID.ServerId.URI` column is blank for any recorders, then something is off with the configuration / state of that recording server and I'm not sure what that would be. If that's the issue, I think this should help you run the camera report by excluding any of those recorders:

```powershell
$recorders = Get-RecordingServer | Where-Object {
    $item = [VideoOS.Platform.Configuration]::Instance.GetItem($_.Id, [VideoOS.Platform.Kind]::Server)
    $null -ne $item.FQID.ServerId.Uri
}
if ($recorders.Count -eq 0) {
    throw "No recorders found in VideoOS.Platform.Configuration.Instance with an FQID.ServerId.URI value"
}
Get-VmsCameraReport -RecordingServer $recorders | Export-Csv ~\Desktop\report.csv
```
