### ISSUE TITLE
Get-Snapshot not working for Hanwha cameras

### ISSUE THREAD

**Issue by henkelsimon** [MilestoneSystemsInc/PowerShellSamples#62]
Get-Snapshot Cmdlet does not seem to work properly for Hanwha cameras. When trying to get a snapshot from live view no snapshot is returned and the following warning is displayed:
`WARNING: No live image available for <CameraName> after -LiveTimeoutMS value of 2000.`

Increasing the timeout parameter value does not resolve the issue. I was able to reproduce the issue with all models of Hanwha cameras we have in use. When running the same code with AXIS cameras I did not encouter any issues.

The cameras seem to all be correctly added to the management server and have an active livestream.

Do you have an insight as to what could be causing the problem?

Module Version 22.1.0

**Comment by joshooaj** [comment]
Do you have Hanwhas version of “h264+“ enabled? What is the I-frame or “key
frame” interval length at the longest if so?

If the keyframe interval is really long (20-30 seconds or more for example)
I wonder if your longest “livetimeoutms” wasn’t long enough to encounter a
keyframe from which a snapshot could be generated?

The Smart Client advanced decoding diagnostics should help you see what the
GOP length is (group of pictures, the number of image frames from one key
frame to the next). If the frames per second is 10 and the GOP length is 30
then you would expect to see a keyframe every 3 seconds for instance.

Obviously even if that’s the issue, you wouldn’t want to wait that long -
just trying to figure out what the situation might be. I think Smart Client
gets the last group of pictures and uses that as a sort of pseudo keyframe
to decode against until the first fresh keyframe arrives and that’s how it
starts rendering the images in the view fairly quick even if you have long
GOP lengths.


Other useful information if that’s not it - camera model, codec,
resolution, firmware and device pack info, snapshot of the relevant stream
settings in management client to get the full picture, device pack version
and recording server version.

Cheers,

Josh

**Comment by henkelsimon** [comment]
Hello Josh

Tank you for your suggestions. I have taken a look at the GOP length of the affected cameras. They all have a GOP length of 6 frames with a framerate of 12 FPS. Which should give me 2 I-frames a second. Which would mean that even with a timeout of just 2 seconds the command should have encountered an I-frame. I have tried increasing the timeout to the maximum value of 30 seconds but as suspected that didn't change anything. 

That leads me to believe that the GOP length is not the issue in this case, so I have gone ahead and added the other infos you mentioned down below:

- Camera Model: Hanwha Techwin XNP-6321H
  - Firmware Version: 2.10.02
  - Codec: H.265
  - Resolution: 1280x720
  - FPS: 12
  - GOP Length: 6

- XProtect Version: 2020 R2 with latest hotfixes installed
  - Recording Server Version: 20.2a
  - Device Pack Version: 11.7a
  - Legacy Device Pack Version: 21b

Stream Settings in Management Client:
![image](https://user-images.githubusercontent.com/108878677/178008424-f6b4fc0e-6e68-4438-a3dd-9d5d5bd55b65.png)

Thank you for your help

Regards,

Simon

**Comment by joshooaj** [comment]
Hi @henkelsimon,

I don't have a Hanwha camera handy that I can change from H264 to H265 to test on, but I tested with H264 on a PNV-A6081R, TNB-9000, and PNV-A9081R, and all three gave me both a live and a recorded image through the `Get-Snapshot` cmdlet.

Are you able to test whether you get a snapshot successfully when the stream is set to H264 instead of H265? It _might_ be a hardware acceleration issue where the MIP SDK is unable to successfully decode the image and convert to JPEG. Another option is to try disabling hardware acceleration in PowerShell before retrieving a snapshot. To do that you can run...

```powershell
[VideoOS.Platform.EnvironmentManager]::Instance.EnvironmentOptions['HardwareDecodingMode'] = 'Off'
[VideoOS.Platform.EnvironmentManager]::Instance.FireEnvironmentOptionsChangedEvent()
```

**Comment by Idefixli** [comment]
Hi @joshooaj 
I'm working also with @henkelsimon together at this problem. With H264 i have no problem to receive the snapshot. 👍 

With disabling hardware acceleration i have no luck to get a snapshot with H265. Not so bad, we will switch all cameras to H264 at the moment anyway, as this also gives less problems with CPU usage.

Thanks a lot for your help. 

Regards
Thomas

**Comment by Silex** [comment]
I have the same problem with an AXIS M4206-LV in H265.

Using H264 works but H265 never even when disabling HardwareDecodingMode.

**Comment by Silex** [comment]
I found out by testing that all cameras that are using H265 do not work with Get-Snapshot.

**Comment by Tarterman** [comment]
As a note, I have an Axis P3265-LVE that supports h.265 and I don't have any problem getting a snapshot using Get-Snapshot.  I tried with it set to h.264 and h.265 and it worked fine for me.  I'm not sure what the difference would be between Silex and I since we were both working on Axis cameras.  I'm running MilestonePSTools 23.1.3.

**Comment by Silex** [comment]
Today on an installation that was sending emails with snapshots on motion detection the same problem happened with H265 cameras. It says that the system must support hardware accelaration but it's failing on system that have NVIDIA GPUs so my guess is that H265 snapshots are kinda broken.

**Comment by joshooaj** [comment]
Hi @Silex,

I discovered this week that software decoding of H.265 video has basically always been broken in MilestonePSTools. The intermittent ability to reproduce the issue seems to come down to whether or not Intel or Nvidia hardware acceleration is available. If software decoding is required, we use an Intel MediaSDK plugin loaded from a DLL in a subdirectory of the executing application. This is fine for Smart Client or other standalone executables, but for MilestonePSTools the executing application is powershell.exe running from the `C:\Windows\System32\...` path.

Here's a link to a more detailed description and temporary solution: https://github.com/MilestoneSystemsInc/PowerShellSamples/issues/126#issuecomment-2125959775

**Comment by Silex** [comment]
Yes, it's been broken in standard XProtect as well for ages now, e.g when having a rule that sends snapshots by email.

Support says it's a graphic driver issue 🤷

**Comment by joshooaj** [comment]
Thanks for letting me know! I bet the fix would be the same for H265 snapshots too - I’ll try to reproduce it this week.

**Comment by Silex** [comment]
@joshooaj FYI this is what the support answer for H265 email snapshots in VMs:

```
Unfortunately it is not possible to have h265 email snapshots works when
the Management/Event server run in a VM without hardware acceleration.
```

**Comment by joshooaj** [comment]
Hmmm, what would they say when the same issue is present on bare metal when no hardware acceleration is available?

Oh well, I think this should be fixed in the next release as I think the responsible dev team indicated they might implement the same fix I implemented for pstools.

**Comment by Silex** [comment]
That would be awesome. It's a "bug" that annoys us since a while now.

**Comment by joshooaj** [comment]
In case you haven't tried it already, it looks like you can make attachments from H.265 streams work by applying the same change to the `AviGen` directory as we made to MilestonePSTools.

## Steps

1. Open your MilestonePSTools module directory. Mine is in `C:\Users\<user>\Documents\WindowsPowerShell\Modules\MilestonePSTools\24.1.10`
2. Inside the `bin` directory, copy the folder `15dd936825ad475ea34e35f3f54217a6`
3. Paste the folder into the `AviGen` directory at `C:\Program Files\Milestone\XProtect Management Server\AviGen\`

![image](https://github.com/user-attachments/assets/fc02ab6c-d8f1-44b8-a3f1-62c0ea26e46d)

![image](https://github.com/user-attachments/assets/3e1e7571-fecf-42f0-a37b-d51cd17735f2)


Now, the next time you send a notification with an image attachment from a camera using H.265, it shouldn't matter whether your Management Server is running on bare metal, or in a VM, with or without hardware acceleration, the image should be attached. I used Papercut to test this locally on a test VMS. The first few notifications had no images attached and the file size of those emails was less than 1KB. Then I copied that directory into the `AviGen` folder and the next email was 743KB thanks to the 5 images of my fingerprint-covered access point.

![image](https://github.com/user-attachments/assets/5d47903b-0bf2-4462-bd37-2a244ee0b961)

**Comment by Silex** [comment]
Yay it works! Thanks 🥳
