### ISSUE TITLE
Can't save storage info

### ISSUE THREAD

**Issue by jamesangi** [MilestoneSystemsInc/PowerShellSamples#68]
Maybe I'm missing something, but I'm trying to configure recording server storage and the changes don't seem to save.  I've tried adjusting both MaxSize and Name, and I've called the Save() method on the individual storage object, the storage folder, and the NVR.

**Comment by joshooaj** [comment]
Hi @jamesangi,

Sorry for the very delayed response! The module is overdue for a `Set-VmsStorage` cmdlet but you should be able to modify the settings for a storage object like this:

```powershell
$storage = Get-VmsRecordingServer -Name 'Recorder1' | Get-VmsStorage | Sort-Object Name | Select-Object -First 1
$storage.MaxSize = 2TB / 1MB # Value is stored in MB
$storage.Save()
```

This would get the first live storage from "Recorder1" and set the maximum size to 2TB. Feel free to re-open the issue if this isn't working for some reason!

**Comment by jamesangi** [comment]
Hmm... That does work.  But that's also exactly what I tried back in August.  I believe I was working on an older Milestone, but I can't remember which customer to try it again.  I'm just glad it's working, thanks for the reponse.
