### ISSUE TITLE
Federated Architecture childs

### ISSUE THREAD

**Issue by OlivierPaget** [MilestoneSystemsInc/PowerShellSamples#7]
Hi Josh
In a Federated Architecture, how can we get the list of Management Children from the Parent Management? 
With Connect-ManagementServer I can add -IncludeChildSites, but it doesn't change the result.
Thank you
Olivier

**Comment by jhendricks123** [comment]
Hi Olivier,

I'm away from my computer but to list the child sites you can use
Select-Site -ListAvailable I believe.

If there are multiple levels and you need the hierarchy, I know you can ask
the management server itself for it's children but I forget how at the
moment. I'll have to tinker later.

/Josh

**Comment by jhendricks123** [comment]
To get a list of sites, you can do...

```powershell
Get-Site -ListAvailable                                                                                                                                          

FQID                   : VideoOS.Platform.FQID
Name                   : MSNODE01
HasChildren            : No
Icon                   :
MapIconKey             : 00000000-0000-0000-0000-000000000000
HasRelated             : No
Properties             : {[URL_Server, http://xprotect.lab.local/], [URL, http://xprotect.lab.local/], [Address, http://xprotect.lab.local/], [Address0,
                         http://xprotect/]...}
Enabled                : True
PositioningInformation :
Authorization          : {}
ContextMenu            : {}
```

and to select a site, you can do...

```powershell
Select-Site -Name MSNODE01
```

or to select from a GUI list...

```powershell
Get-Site -ListAvailable | Out-GridView -Title "Select a site" -OutputMode Single | Select-Site
```

Finally if you want to walk the hierarchy yourself you can do this...

```powershell
$currentSite = Get-Site
foreach ($childSite in $currentSite.GetChildren()) {
    # do work
}
```
