### ISSUE TITLE
Get-VmsLog doesn't call "-Complete" on Write-Progress

### ISSUE THREAD

**Issue by Tarterman** [MilestoneSystemsInc/PowerShellSamples#72]
If you call Get-VmsLog you get the progress bar.  However, when it is finished getting the logs, it seems like it isn't doing Write-Progress again with "-Complete" to clear the bar.  This causes the progress bar to continue to be shown until the entire script is completed.

As a quick test, you can do this:

`$log = Get-VmsLog; Start-Sleep -Seconds 15`

**Comment by joshooaj** [comment]
Fixed in 22.3.0
