### ISSUE TITLE
Move camera from Recording Server

### ISSUE THREAD

**Issue by MirkoAAa** [MilestoneSystemsInc/PowerShellSamples#73]
Hi, just one question. Can the camera be moved from one recording server to another recording server? If it is possible, how?

**Comment by joshooaj** [comment]
Hi @MirkoAAa,

There is no function built-in to MilestonePSTools for moving hardware between recording servers yet, but it can be done using MilestonePSTools and the [MoveHardware method](https://doc.developer.milestonesys.com/html/index.html?base=miphelp/class_video_o_s_1_1_platform_1_1_configuration_items_1_1_hardware.html&tree=tree_search.html?search=movehardware) attached to the Hardware objects themselves.

Perhaps this will be added to the module later, but I put together a separate module file with a Move-VmsHardware function. It works well in my test environment - feel free to have a look and use at your own risk.

Note that I discovered a bug that may or may not already be resolved with a cumulative patch - I will look into it next week. It appears that the destination storage ID can be _any valid storage ID_ even if the associated storage is not on the destination recording server. This probably means that the cameras would not be able to record after being moved. I check for this in the example linked below and do not allow the move to proceed if the destination storage is not associated with the destination recorder.

To use this example, you would save the .PSM1 file to a machine with MilestonePSTools installed. Then use `Import-Module -Path C:\path\to\Move-VmsHardware.psm1`. With this done, you can use `Connect-ManagementServer` to login and then use the custom `Move-VmsHardware` function. The example has documentation which you can see in the link below or use `Get-Help Move-VmsHardware -Full` after importing the module.

https://gist.github.com/joshooaj/8bf15e5e49e1980d3984de747e6b1501

**Comment by MirkoAAa** [comment]
Thank you very much it is just what I was looking for!

**Comment by joshooaj** [comment]
Happy to help 😃
