### ISSUE TITLE
Import-VmsHardware when using FQDN names

### ISSUE THREAD

**Issue by phumborstad** [MilestoneSystemsInc/PowerShellSamples#75]
Hi,
Ran into an issue with importing from csv file. 
In the file we had the following(with headers)

```text
Address,Username,Password,Drivernumber,DriverFamily,HardwareName,CameraName,Speakername,MicrophoneName,MetadateName,InputName,OutputName,CameraGroup,Description,RecordingServer
site-itv-006979.actualdomainredacted.no,root,redacted,806,AXIS,site-itv-006979,site-itv-006979 - fb subsitename,site-itv-006979 - fb subsitename,site-itv-006979 - fb subsitename,site-itv-006979 - fb subsitename,site-itv-006979 - fb subsitename,site-itv-006979,sitename,006979,ITV-REC54.actualdomainredacted.local
```

This does not work, but when adding http:// to address it works.
It adds the camera, but looses the Hardware and CameraName on the way.
When adding with IP instead of FQDN it works without https://

Figured it out, but thought someone should look into this.

**Comment by joshooaj** [comment]
Thanks for the heads up! I'm preparing to push the next MilestonePSTools version to PSGallery and I'll try to dig into this before publishing to see if there's a fix I can include first.

**Comment by joshooaj** [comment]
Thanks again for reporting this issue - version 22.3.0 is now published to PSGallery!
