### ISSUE TITLE
Programmatically "Replace Hardware"

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#76]
Hello,

On some (old) cameras, when changing stream settings most of the time everything is correct but the camera refuses to give a stream.

The fix is quite simple, "Replace Hardware" then next next next and everything is fine.

It'd be nice to have a trick to do that programmaticaly - anything goes. I'm thinking maybye stopping the recording server and deleting some cache or whatever "Replace Hardware" magic does.

**Comment by joshooaj** [comment]
Hi @Silex,

The Configuration API in 2023 R1 will support simple replace-hardware scenarios. You won't be able to programmatically assign "old camera 1" to "new camera 3" like you can in the Management Client wizard for example, but that's not a really common scenario. I think the plan is that you would make sure the channels you won't use are disabled prior to the replacement, and the channels from the source will be mapped to the channels in the destination driver in order by channel number.

I've already written up a function named `Set-VmsHardwareDriver` to make this easy to use in MilestonePSTools and it'll be released with the 23.1.0 release soon after the new version is available.
