### ISSUE TITLE
PSTools commands

### ISSUE THREAD

**Issue by Nimtek123** [MilestoneSystemsInc/PowerShellSamples#8]
Hi Josh

I would like to get the following info please help.

Total Capacity per server used/ free
Recording status count
Most recurring Offline Alarm/ Alarms and status( online/offline)
Most utilised cameras
Number of logins
Number of system changes made (Added devices/ removed devices)
Last Backup
How many exports were made
Number of views
Number of active users

**Comment by jhendricks123** [comment]
Hi Nimtek,

Sorry for the late reply. These bullets require quite a bit more discussion to understand exactly what is needed and advise on how to achieve those goals, but the intent of this issues section is to give people a place to post MilestonePSTools feature requests or report bugs/questions regarding specific cmdlets. I'll do my best to give you some tips on where to start though.

- Total Capacity per server used/ free
  - When using MIP SDK it's not currently possible to get actual HDD used/free information, but you can read the storage configuration properties to see what the user-specified capacity of a storage configuration is, and you can call ReadStorageInformation() or ReadArchiveStorageInformation() to pull the UsedSpace and LockedUsedSpace which is the disk space used in MB for data that has been evidence locked.
  `Get-RecordingServer | % { $rec = $_; ($rec.StorageFolder.Storages.ReadStorageInformation() | Get-ConfigurationItem).Properties | Select Key, Value }`
- Recording status count
  - I'm not sure what this is, but Get-ItemState will return a fairly generic status like "Responding", "Not Responding" and so on.
- Most recurring Offline Alarm/ Alarms and status( online/offline)
  - Again it depends on what you're looking for specifically - for example you can get a lot of information from Get-Log about cameras/servers going online/offline. If you specifically want to look at alarms which have been generated from one or more alarm definitions made in Management Client, or generated by 3rd party integrations, you'll need to use MIP SDK components like the AlarmClientManager. The MIP SDK documentation can be found at https://doc.developer.milestonesys.com/html/index.html
- Most utilised cameras
  - I don't know what "most utilized" means. Most viewed I guess? This statistic isn't readily available but you could use the Audit log (from Get-Log) and generate some statistics from there?
- Number of logins
  - Use Get-Log to enumerate through the audit logs. You might want to make sure user access logging is enabled for the audit log to get more detailed info. This checkbox is in Management Client under Tools > Options > Server Logs > Audit logs
- Number of system changes made (Added devices/ removed devices)
  - You might have to run a daily report or something to gather the statistics you're interested in, and do a diff from previous days reports to see what changed?
- Last Backup
  - Last backup of what? The configuration backup in Management Client? If you have a specific backup strategy in mind, I would implement that directly in MSSQL. SQL will be a much better place to schedule and track backup progress/completion and do reporting.
- How many exports were made
  - I believe you can get this information in the audit log if user access logging is enabled. You'll need to parse it out from Get-Log.
- Number of views
  - Number of views of what? The number of views created in Smart Client? This is not easy to do, but somewhat possible through MIP SDK. If you play with the IServerCommandService interface, you have GetViewGroups(token) and GetViewGroupData(token, viewgroupId) methods. This isn't quite a public interface in the SDK so the documentation is thin, but you can get the XML content of _public_ view groups which define groups, views and view items.
- Number of active users
  - There's not a good way to do this with MIP SDK just yet. Some crude methods include using the Audit log or the Get-WhoIsOnline cmdlet, but neither of these are perfect. A less than ideal method could be do look at the dbo.Tokens table in the Surveillance database and match the token up with the identity in the dbo.SecurityIdentity table. But going direct to SQL is something you should try to avoid whenever possible, and by default tokens are good for 4 hours so you're going to see tokens for users who may have disconnected some time ago.
