### ISSUE TITLE
Manipulate "Automatically Retrieve Remote Recordings when connection is Restored" checkbox via PSTools

### ISSUE THREAD

**Issue by bmax1985** [MilestoneSystemsInc/PowerShellSamples#80]
Hello,
I am working to script a periodic check of camera configuration throughout our enterprise and ensure that cameras are configured to automatically function with edge retrieval.  I have found fields for everything but the checkbox that exists on the camera configuration for "Automatically Retrieve Remote Recordings when connection is Restored".

Can this be manipulated within this framework or is another user aware of a method that I may use to confirm it's checked and if not, enable it?

This will be the early stages of confirming that edge retrieval is actually working which will be part of the larger initiative.  For the time being, I'm looking for reporting and mass configuration where needed.

**Comment by joshooaj** [comment]
Hi @bmax1985,

Does `Set-VmsCamera -EdgeStorageEnabled $true` do what you need? It toggles the checkbox in the screenshot below. If you wanted to make sure every enabled camera had that value set to `$true` you could run the line below with `-WhatIf` to see what it would do, and then remove `-WhatIf` if you actually want to make the changes.

```powershell
Get-VmsCamera | Set-VmsCamera -EdgeStorageEnabled $true -WhatIf
```

![image](https://user-images.githubusercontent.com/7669972/217392855-aaaddc31-719b-4adf-8680-198dfa13d210.png)

**Comment by bmax1985** [comment]
Thank you.  That got me on the right track.  I didn't figure edge was disabled and was looking for something around retrieval.
