### ISSUE TITLE
Get-VmsCameraReport Error: "The value cannot be null"

### ISSUE THREAD

**Issue by ISGNordicMNI** [MilestoneSystemsInc/PowerShellSamples#82]
MilestonePSTools Version: 22.3.0

Milestone version: 21.2.0.1
Recording server ver: 21.2a Build: 1877

When im trying to Get-VmsCameraReport i get the error thrown,

```
PS C:\Users\myuser> Get-VmsCameraReport | Out-GridView
Cannot convert value "System.Collections.Hashtable" to type "LocalJobRunner". Error: "Value cannot be null.
Parameter name: name"
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\22.3.0\MilestonePSTools.psm1:8223 char:9
+         $jobRunner = [LocalJobRunner]@{
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException

Foreach-Object : You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\22.3.0\MilestonePSTools.psm1:8260 char:52
+             $fillChildrenJobs = $RecordingServer | Foreach-Object {
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.ForEachObjectCommand
 ```

Been trying to look for any kind of similar issue without any success so i thought i'd ask as i am unsure why this is happening

**Comment by joshooaj** [comment]
I'm not sure if you're the same person I worked with on this same error recently but I observed someone's aggressive endpoint protection / antivirus software causing this error among others.

It was silently preventing the execution of certain elements of the module and either the customer didn't have access to the AV logs to confirm, or there was no obvious record of the interference. But once the endpoint protection was disabled, the module worked great.

Any chance you could be in a similar situation?
