### ISSUE TITLE
Video Export question

### ISSUE THREAD

**Issue by jstack49** [MilestoneSystemsInc/PowerShellSamples#85]
When using the video export function, wondering if it's possible to include the Smart Client player with DB exports in the same manner that can be done from Smart Client. We need to provide a stand alone player to end users without access to any XProtect systems. 
I've been attempting to figure this out by comparing the output of a SC generated export with one from PSTools, so far no luck.

Any guidance would be appreciated, great work on the PSTools module!

Thanks........Jeff

**Comment by joshooaj** [comment]
Hi Jeff,

I'd love to offer this in MilestonePSTools but it isn't supported in the SDK. Without that, it would require a Smart Client installation or a copy of a Smart Client player, and we'd need to reproduce the way Smart Client packages up the player.

The DB export format produces a .SCP file (if I recall correctly) which describes a smart client player "project". If Smart Client is installed, then the extension is configured to launch using the installed Smart Client player.

It may be possible to copy an installation of Smart Client with the export and make a BAT/CMD/EXE that launches the .SCP file with the manually packaged client? It's worth exploring, but I may not have time to look into it for a little while.
