### ISSUE TITLE
Milestone VMS Camera Non-Responding

### ISSUE THREAD

**Issue by saw0ne** [MilestoneSystemsInc/PowerShellSamples#87]
I am running a demo with a 3rd party monitoring software that runs a data connector to the Milestone VMS. When I disconnect an IP camera from the network, I found that the app still shows its status as "connected."

I received this answer from a developer below.

This is a known problem condition with Milestone because it is not reporting the camera as “not connected” and continues to stream this last image as the image for that camera. 

I am trying to verify if this is the case.  When I run vmscameraReport, I see that the camera state is 'not Responding'

Thanks,
-Saw

**Comment by joshooaj** [comment]
I believe this technology partner reached out to us and I had a productive conversation with them last week. Ultimately I think they will be implementing support for the RecorderStatusService2 recording server interface and the GetCurrentDeviceStatus method, or something similar. They're a sharp group of people and I'm confident they'll sort this out fairly quickly 👍
