### ISSUE TITLE
New-Object : Cannot find type [System.Collections.Generic.List[LocalJob]]: 

### ISSUE THREAD

**Issue by codypaternostro** [MilestoneSystemsInc/PowerShellSamples#90]
Having a similar issue to " Get-VmsCameraReport Error: "The value cannot be null" #82 ". 

Currently reworked Get-CameraReport2 to work with screenshots as an alternative for Excel reports. I would love to be able to use Get-VmsCameraReport for speed and efficiency. Both the client and host in this example are updated to meet the requirements based on the specifications from the installation page. https://www.milestonepstools.com/installation/#requirements 

```
Get-VmsCameraReport
New-Object : Cannot find type [System.Collections.Generic.List[LocalJob]]: verify that the assembly containing this type is loaded.
At line:32 char:18
+         return @(& $origNewObject @psBoundParameters)
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'JobPollingInterval' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\23.1.3\MilestonePSTools.psm1:9530 char:9
+         $jobRunner.JobPollingInterval = [timespan]::FromMilliseconds( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Foreach-Object : You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\23.1.3\MilestonePSTools.psm1:9565 char:52
+             $fillChildrenJobs = $RecordingServer | Foreach-Object {
+                                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.Commands.ForEachObjectCommand 

```
```
Get-Module -Name MilestonePSTools

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     23.1.3     MilestonePSTools                    {Add-Bookmark, Add-EvidenceLock, Add-GenericEvent, Add-RegisteredService...}

```

**Comment by joshooaj** [comment]
Hey @codypaternostro, I came across your video on youtube today - nice work!

I have indeed seen a few people report issues with their endpoint protection software blocking some of the classes defined in `MilestonePSTools.psm1` but I don't have an environment where I can reproduce it and I haven't come across any solutions yet.

Did you end up tracking down a way to whitelist the module with your antivirus or did you just work around it?

**Comment by codypaternostro** [comment]
Josh!

I had an incredible time working with your module during my internship. This is the direct email I had from the company that was the middleman for Sentinel One.

“Cody,

The explanation that I received is that the powershell command is being monitored by S1, during the monitoring process it is causing a delay or pause during commands and that is breaking the whole package. S1 is technically not sopping the process or blocking anything, but the delay is apparently the root cause of that.”

To my knowledge, the solution was to whitelist PowerShell entirely. When I was testing with them the only time Get-VmsCameraReport was working when was S1 was deactivated.

Once again, such an in incredible module and usage of multi-threading. I learned so much looking through the code!


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joshooaj** [comment]
Nice, thanks for sharing S1's response and I'm stoked that you were able to put the module to use during your internship! I'm relatively new to PowerShell myself, having started in 2019 with this module, and it's been an incredibly useful skill.

If you're ever interested in a job, feel free to reach out 🤘🏼
