### ISSUE TITLE
Set-VmsRoleOverallSecurity can not set Alarm Management Security Settings

### ISSUE THREAD

**Issue by maxmantis** [MilestoneSystemsInc/PowerShellSamples#95]
I am trying to use MilestonePSTools to set the alarm management security setting properties of a role, i.e. allow a role to view and manage alarms. I am following [Example 1](https://www.milestonepstools.com/functions/set-vmsroleoverallsecurity/#example-1) of the documentation of `Set-VmsRoleOverallSecurity`. 

Using version 23.1.3 of MilestonePSTools with XProtect Corporate 2022 R1 everything works as expected. The SecurityNamespace "Alarms" has the properties `GENERIC_READ` and `GENERIC_WRITE` which we can set to 'Allow'. Running the PowerShell script
```
Connect-ManagementServer -ServerAddress $ServerIpAddress
New-VmsRole -Name TestRole
$alarmPermissions = Get-VmsRoleOverallSecurity -Role TestRole -SecurityNamespace Alarms
echo $alarmPermissions.Keys
$alarmPermissions.GENERIC_READ = 'Allow'
$alarmPermissions.GENERIC_WRITE = 'Allow'
Set-VmsRoleOverallSecurity -Permissions $alarmPermissions
```
returns

> Name                 RoleType       SmartClient  WebClient    MobileClient LastModified         Id
    ----                 --------       -----------  ---------    ------------ ------------         --
    TestRole             UserDefined    False        False        False        7/19/2023 9:20:04 AM ...
    <br>
    SecurityNamespace
     GENERIC_WRITE
    GENERIC_READ
    ADMIN_SECURITY
    Role
    GENERIC_DISABLE
    GENERIC_NOTIFY
    DisplayName

and the corresponding boxes for "View" and "Manage" in the ManagementClient are ticked.

However, with MilestonePSTools and XProtect Professional+ 2023 R1 this does not work anymore. Running the same script does not change the alarm permissions and returns

> Name                 RoleType       SmartClient  WebClient    MobileClient LastModified         Id
    ----                 --------       -----------  ---------    ------------ ------------         --
    TestRole             UserDefined    False        False        False        7/18/2023 5:49:55 PM ...
    <br>
    SecurityNamespace  
    DisplayName
    Role
    <br>
    WARNING: Attribute 'GENERIC_READ' not found in SecurityNamespace
    WARNING: Attribute 'GENERIC_WRITE' not found in SecurityNamespace

How to set the alarm management settings in the Management Client has also changed. In the  2023 R1 Management Client one can set them via Roles->TestRole->Alarms->Allow Manage&View compared to Roles->TestRole->**OverallSecurity**->Alarms->Allow Manage&View in the 2022 R1 Management Client.

Is there any way to allow a role to manage and view alarms with MilestonePSTools and the 2023R1 version? If not, could this be fixed/added?

**Comment by joshooaj** [comment]
Hi @maxmantis,

If this worked differently prior to 2023 R1, it seems this is a change in how alarm permissions are managed in the VMS and there's nothing we can do within the MilestonePSTools module to overcome that.

Looking at my 2023 R2 test system, I too see the Alarms overall security namespace lacks any security attributes when I downgrade it to either Professional+ or Expert. When I bump it back to Corporate, all the `Generic_*` attributes are available again - both in PowerShell / Configuration API, and in the Management Client.

I'll check around to see if that was an intentional change and post back later!

**Comment by maxmantis** [comment]
Thanks for the response @joshooaj, I'm looking forward to an update when you have more information!

**Comment by joshooaj** [comment]
Is it possible that this was never a _product version_ difference but a _product tier_ difference? I can reproduce the behavior by switching between an XProtect Corporate and XProtect Expert license on 2023 R2 as well as 2020 R2. I believe the reason the overall security permission namespace is missing on XProtect Expert and lower is that it includes the "Manage security" permission which would likely fall under "differentiated administration security settings" which is only available on XProtect Corporate.

The next obvious question is "how do I manage permissions for alarms then?" and frustratingly, I don't think MIP SDK provides a mechanism for this yet. I know we can manage overall security, and device-level security, but I don't think the APIs provide a way to manipulate permissions for all the other resources for which there are tabs on each role. I'm checking on this though and will of course advocate for it to be added in a future release.

I can see that when I enable the "Disable alarms" permission on the Alarms tab of a role, an entry is created in the Surveillance.dbo.SecurityAccessEntry table for security_object_id 76921911-B104-4404-9F44-7442F7592737 which must map to the Alarms resource. The user_sid GUIDs in the screenshot below are the ID's of the two roles I tested this with. But manually adding/changing data in the SQL database is not supported, nor for the faint of heart.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/cd15ecbd-705f-45ef-88c4-7f30ebe48b85)

**Comment by maxmantis** [comment]
Thanks for the update!

From this information it indeed looks likely that the issue is due to a product tier difference. Unfortunately, using an XProtect Corporate license is not feasible for us, so we rely on a solution that works with Xprotect Professional.

**Comment by joshooaj** [comment]
Good news! If upgrading to a future release is an option anyway 😃 

I'm told the plan is to support management of permissions for alarms and any other "MIP Items" through our APIs starting with the 2023 R3 release. If that capability lands in R3 then I think that'd be in October.

**Comment by maxmantis** [comment]
I had a quick look at the APIs but did not find a way to set the alarm permissions of a VMS role at first or second glance. I would greatly appreciate if you could confirm whether the capability was included in the 2023 R3 release and, in case it was, could maybe provide me with a pointer to the API I would need to use. Thanks in advance!

**Comment by joshooaj** [comment]
Hi @maxmantis,

We have access to the Alarm Definitions and Alarms overall security namespaces:

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/b368d12d-9aaf-4a75-92cc-f08691d631bf)


```powershell
$role = Get-VmsRole -RoleType UserDefined | Select-Object -First 1

$alarms = $role | Get-VmsRoleOverallSecurity -SecurityNamespace Alarms
$alarms.GENERIC_READ = 'Allow'
$role | Set-VmsRoleOverallSecurity -Permissions $alarms -Verbose -WhatIf

$definitions = $role | Get-VmsRoleOverallSecurity -SecurityNamespace 'Alarm Definitions'
$definitions.GENERIC_READ = 'Allow'
$role | Set-VmsRoleOverallSecurity -Permissions $definitions -Verbose -WhatIf
```

Unfortunately the MIP SDK doesn't currently provide access to the more granular permissions in the "Alarms" tab:

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/980c9bae-2c3f-4612-8ed4-c7e7127007b6)

**Comment by maxmantis** [comment]
Is it possible that the security namespace 'Alarms' is not available in XProtect Express+ 2023 R3?


```
$role | Set-VmsRoleOverallSecurity -Permissions $alarms -Verbose -WhatIf
$alarms = $role | Get-VmsRoleOverallSecurity -SecurityNamespace Alarms
$alarms.GENERIC_READ = 'Allow'
```
returns
```
WARNING: Attribute 'GENERIC_READ' not found in SecurityNamespace
```
and in the Management Client, under Overall Security, the 'Alarms' also do not show up:
![overall_security_express_r3](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/117184357/7e85245f-747d-409f-af39-c96994ef2d79)

The 'Alarm Definitions' are accessible in both the Mangement Client and with `Get-VmsRoleOverallSecurity`, but unfortunately allowing permission for those does not solve our use case.

In that case, am I understanding correctly that we have to set the permission to manage & view alarms manually in the 'Alarms' tab of the role in the management client, or is there any other possibility?

**Comment by joshooaj** [comment]
Hmmm, yeah I think the alarms entry may be limited to Corporate and maybe Expert, I can't remember. I think it's connected with "Differentiated administrator rights" or something similar, so the license level determines whether that overall security namespace is available.

Unfortunately until the MIP API provides a way to access all the other permission areas, the alarm permissions may be something that you need to manage by hand. If you're brave, you can dive into the dbo.Security* tables in the Surveillance SQL database or the stored procedures and track down how to make that change directly in the database but it's not something we're able to offer guidance on (I'd have to reverse engineer it or read through source code myself as well).

**Comment by maxmantis** [comment]
Thanks for the insights and the pointer to the `dbo.Security*` tables! We will investigate a bit whether to go in that direction or whether we find a different workaround.
