### ISSUE TITLE
Move cameras from one Recorder to another

### ISSUE THREAD

**Issue by subbuun** [MilestoneSystemsInc/PowerShellSamples#96]
Is there a way to move the cameras in bulk from one to another recorders like the Set-MilestoneNames.ps1 having the columns Current Recorder Name and New Recorder Name.

**Comment by Tarterman** [comment]
The functionality isn't build into MilestonePSTools at this point.  The APIs support it though so it is possible but just not something that has been prioritized.  However, you can bulk move hardware in the Management Client by right-clicking on the Recording Server and choosing Move Hardware.  You'll then be presented with an option of choosing the hardware and what Recording Server you want to move it too.

**Comment by subbuun** [comment]
Thanks Jared.


________________________________
