### ISSUE TITLE
Exporting & Importing Camera Shortcut

### ISSUE THREAD

**Issue by subbuun** [MilestoneSystemsInc/PowerShellSamples#99]
Can you please advise on exporting the Camera Shortcut from the Cameras->Client TAB and importing it back after updating the CSV ?

**Comment by Tarterman** [comment]
You can do something like this to get the Shortcut.

The camera shortcut is stored in the ClientSettings folder.  So, if you have a camera object set to a variable called $cam, you can get the shortcut like this:

```
$cam.ClientSettingsFolder.ClientSettings[0].Shortcut
```

If you are storing it to a CSV to be pulled back in later, I would recommend checking if the shortcut value equal 0 or is null or empty ([string]::IsNullOrEmpty($cam.ClientSettingsFolder.ClientSettings[0].Shortcut).  If it is 0 or it is null or empty, store the value as blank in the CSV.  Then, when you are pulling it back in, check if the value in the CSV is blank.  If it is, then skip setting the value.

If you don't do this, the value will be set as 0 when you do the export and then applied as 0 when you do the import so any cameras that don't have a shortcut will end up getting a shortcut value of 0.
